// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: dag.proto

package scenario_service

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DAGService_Create_FullMethodName                     = "/scenario_service.DAGService/Create"
	DAGService_Get_FullMethodName                        = "/scenario_service.DAGService/Get"
	DAGService_GetAll_FullMethodName                     = "/scenario_service.DAGService/GetAll"
	DAGService_Delete_FullMethodName                     = "/scenario_service.DAGService/Delete"
	DAGService_Update_FullMethodName                     = "/scenario_service.DAGService/Update"
	DAGService_CreateScenario_FullMethodName             = "/scenario_service.DAGService/CreateScenario"
	DAGService_GetScenarioHistory_FullMethodName         = "/scenario_service.DAGService/GetScenarioHistory"
	DAGService_SelectManyScenarioVersions_FullMethodName = "/scenario_service.DAGService/SelectManyScenarioVersions"
	DAGService_RevertScenario_FullMethodName             = "/scenario_service.DAGService/RevertScenario"
)

// DAGServiceClient is the client API for DAGService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DAGServiceClient interface {
	Create(ctx context.Context, in *CreateDAGRequest, opts ...grpc.CallOption) (*DAG, error)
	Get(ctx context.Context, in *GetDAGRequest, opts ...grpc.CallOption) (*DAG, error)
	GetAll(ctx context.Context, in *GetAllDAGRequest, opts ...grpc.CallOption) (*DAGList, error)
	Delete(ctx context.Context, in *DeleteDAGRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	Update(ctx context.Context, in *CreateScenarioRequest, opts ...grpc.CallOption) (*DAG, error)
	CreateScenario(ctx context.Context, in *CreateScenarioRequest, opts ...grpc.CallOption) (*DAG, error)
	GetScenarioHistory(ctx context.Context, in *GetScenarioHistoryRequest, opts ...grpc.CallOption) (*GetScenarioHistoryResponse, error)
	SelectManyScenarioVersions(ctx context.Context, in *CommitWithRelease, opts ...grpc.CallOption) (*CommitWithRelease, error)
	RevertScenario(ctx context.Context, in *RevertScenarioRequest, opts ...grpc.CallOption) (*RevertScenarioResponse, error)
}

type dAGServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDAGServiceClient(cc grpc.ClientConnInterface) DAGServiceClient {
	return &dAGServiceClient{cc}
}

func (c *dAGServiceClient) Create(ctx context.Context, in *CreateDAGRequest, opts ...grpc.CallOption) (*DAG, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DAG)
	err := c.cc.Invoke(ctx, DAGService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dAGServiceClient) Get(ctx context.Context, in *GetDAGRequest, opts ...grpc.CallOption) (*DAG, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DAG)
	err := c.cc.Invoke(ctx, DAGService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dAGServiceClient) GetAll(ctx context.Context, in *GetAllDAGRequest, opts ...grpc.CallOption) (*DAGList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DAGList)
	err := c.cc.Invoke(ctx, DAGService_GetAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dAGServiceClient) Delete(ctx context.Context, in *DeleteDAGRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, DAGService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dAGServiceClient) Update(ctx context.Context, in *CreateScenarioRequest, opts ...grpc.CallOption) (*DAG, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DAG)
	err := c.cc.Invoke(ctx, DAGService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dAGServiceClient) CreateScenario(ctx context.Context, in *CreateScenarioRequest, opts ...grpc.CallOption) (*DAG, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DAG)
	err := c.cc.Invoke(ctx, DAGService_CreateScenario_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dAGServiceClient) GetScenarioHistory(ctx context.Context, in *GetScenarioHistoryRequest, opts ...grpc.CallOption) (*GetScenarioHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetScenarioHistoryResponse)
	err := c.cc.Invoke(ctx, DAGService_GetScenarioHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dAGServiceClient) SelectManyScenarioVersions(ctx context.Context, in *CommitWithRelease, opts ...grpc.CallOption) (*CommitWithRelease, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitWithRelease)
	err := c.cc.Invoke(ctx, DAGService_SelectManyScenarioVersions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dAGServiceClient) RevertScenario(ctx context.Context, in *RevertScenarioRequest, opts ...grpc.CallOption) (*RevertScenarioResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevertScenarioResponse)
	err := c.cc.Invoke(ctx, DAGService_RevertScenario_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DAGServiceServer is the server API for DAGService service.
// All implementations must embed UnimplementedDAGServiceServer
// for forward compatibility.
type DAGServiceServer interface {
	Create(context.Context, *CreateDAGRequest) (*DAG, error)
	Get(context.Context, *GetDAGRequest) (*DAG, error)
	GetAll(context.Context, *GetAllDAGRequest) (*DAGList, error)
	Delete(context.Context, *DeleteDAGRequest) (*empty.Empty, error)
	Update(context.Context, *CreateScenarioRequest) (*DAG, error)
	CreateScenario(context.Context, *CreateScenarioRequest) (*DAG, error)
	GetScenarioHistory(context.Context, *GetScenarioHistoryRequest) (*GetScenarioHistoryResponse, error)
	SelectManyScenarioVersions(context.Context, *CommitWithRelease) (*CommitWithRelease, error)
	RevertScenario(context.Context, *RevertScenarioRequest) (*RevertScenarioResponse, error)
	mustEmbedUnimplementedDAGServiceServer()
}

// UnimplementedDAGServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDAGServiceServer struct{}

func (UnimplementedDAGServiceServer) Create(context.Context, *CreateDAGRequest) (*DAG, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedDAGServiceServer) Get(context.Context, *GetDAGRequest) (*DAG, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedDAGServiceServer) GetAll(context.Context, *GetAllDAGRequest) (*DAGList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedDAGServiceServer) Delete(context.Context, *DeleteDAGRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedDAGServiceServer) Update(context.Context, *CreateScenarioRequest) (*DAG, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedDAGServiceServer) CreateScenario(context.Context, *CreateScenarioRequest) (*DAG, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateScenario not implemented")
}
func (UnimplementedDAGServiceServer) GetScenarioHistory(context.Context, *GetScenarioHistoryRequest) (*GetScenarioHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetScenarioHistory not implemented")
}
func (UnimplementedDAGServiceServer) SelectManyScenarioVersions(context.Context, *CommitWithRelease) (*CommitWithRelease, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SelectManyScenarioVersions not implemented")
}
func (UnimplementedDAGServiceServer) RevertScenario(context.Context, *RevertScenarioRequest) (*RevertScenarioResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevertScenario not implemented")
}
func (UnimplementedDAGServiceServer) mustEmbedUnimplementedDAGServiceServer() {}
func (UnimplementedDAGServiceServer) testEmbeddedByValue()                    {}

// UnsafeDAGServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DAGServiceServer will
// result in compilation errors.
type UnsafeDAGServiceServer interface {
	mustEmbedUnimplementedDAGServiceServer()
}

func RegisterDAGServiceServer(s grpc.ServiceRegistrar, srv DAGServiceServer) {
	// If the following call pancis, it indicates UnimplementedDAGServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DAGService_ServiceDesc, srv)
}

func _DAGService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDAGRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DAGServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DAGService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DAGServiceServer).Create(ctx, req.(*CreateDAGRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DAGService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDAGRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DAGServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DAGService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DAGServiceServer).Get(ctx, req.(*GetDAGRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DAGService_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllDAGRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DAGServiceServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DAGService_GetAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DAGServiceServer).GetAll(ctx, req.(*GetAllDAGRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DAGService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDAGRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DAGServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DAGService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DAGServiceServer).Delete(ctx, req.(*DeleteDAGRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DAGService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateScenarioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DAGServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DAGService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DAGServiceServer).Update(ctx, req.(*CreateScenarioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DAGService_CreateScenario_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateScenarioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DAGServiceServer).CreateScenario(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DAGService_CreateScenario_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DAGServiceServer).CreateScenario(ctx, req.(*CreateScenarioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DAGService_GetScenarioHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetScenarioHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DAGServiceServer).GetScenarioHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DAGService_GetScenarioHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DAGServiceServer).GetScenarioHistory(ctx, req.(*GetScenarioHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DAGService_SelectManyScenarioVersions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitWithRelease)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DAGServiceServer).SelectManyScenarioVersions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DAGService_SelectManyScenarioVersions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DAGServiceServer).SelectManyScenarioVersions(ctx, req.(*CommitWithRelease))
	}
	return interceptor(ctx, in, info, handler)
}

func _DAGService_RevertScenario_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevertScenarioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DAGServiceServer).RevertScenario(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DAGService_RevertScenario_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DAGServiceServer).RevertScenario(ctx, req.(*RevertScenarioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DAGService_ServiceDesc is the grpc.ServiceDesc for DAGService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DAGService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scenario_service.DAGService",
	HandlerType: (*DAGServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _DAGService_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _DAGService_Get_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _DAGService_GetAll_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _DAGService_Delete_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _DAGService_Update_Handler,
		},
		{
			MethodName: "CreateScenario",
			Handler:    _DAGService_CreateScenario_Handler,
		},
		{
			MethodName: "GetScenarioHistory",
			Handler:    _DAGService_GetScenarioHistory_Handler,
		},
		{
			MethodName: "SelectManyScenarioVersions",
			Handler:    _DAGService_SelectManyScenarioVersions_Handler,
		},
		{
			MethodName: "RevertScenario",
			Handler:    _DAGService_RevertScenario_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dag.proto",
}
