// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: docx_template.proto

package template_service

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DocxTemplateService_CreateDocxTemplate_FullMethodName    = "/docx_template_service.DocxTemplateService/CreateDocxTemplate"
	DocxTemplateService_GetListDocxTemplate_FullMethodName   = "/docx_template_service.DocxTemplateService/GetListDocxTemplate"
	DocxTemplateService_GetSingleDocxTemplate_FullMethodName = "/docx_template_service.DocxTemplateService/GetSingleDocxTemplate"
	DocxTemplateService_UpdateDocxTemplate_FullMethodName    = "/docx_template_service.DocxTemplateService/UpdateDocxTemplate"
	DocxTemplateService_DeleteDocxTemplate_FullMethodName    = "/docx_template_service.DocxTemplateService/DeleteDocxTemplate"
)

// DocxTemplateServiceClient is the client API for DocxTemplateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DocxTemplateServiceClient interface {
	CreateDocxTemplate(ctx context.Context, in *CreateDocxTemplateReq, opts ...grpc.CallOption) (*DocxTemplate, error)
	GetListDocxTemplate(ctx context.Context, in *GetListDocxTemplateReq, opts ...grpc.CallOption) (*GetListDocxTemplateRes, error)
	GetSingleDocxTemplate(ctx context.Context, in *GetSingleDocxTemplateReq, opts ...grpc.CallOption) (*DocxTemplate, error)
	UpdateDocxTemplate(ctx context.Context, in *UpdateDocxTemplateReq, opts ...grpc.CallOption) (*DocxTemplate, error)
	DeleteDocxTemplate(ctx context.Context, in *DeleteDocxTemplateReq, opts ...grpc.CallOption) (*empty.Empty, error)
}

type docxTemplateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDocxTemplateServiceClient(cc grpc.ClientConnInterface) DocxTemplateServiceClient {
	return &docxTemplateServiceClient{cc}
}

func (c *docxTemplateServiceClient) CreateDocxTemplate(ctx context.Context, in *CreateDocxTemplateReq, opts ...grpc.CallOption) (*DocxTemplate, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DocxTemplate)
	err := c.cc.Invoke(ctx, DocxTemplateService_CreateDocxTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *docxTemplateServiceClient) GetListDocxTemplate(ctx context.Context, in *GetListDocxTemplateReq, opts ...grpc.CallOption) (*GetListDocxTemplateRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetListDocxTemplateRes)
	err := c.cc.Invoke(ctx, DocxTemplateService_GetListDocxTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *docxTemplateServiceClient) GetSingleDocxTemplate(ctx context.Context, in *GetSingleDocxTemplateReq, opts ...grpc.CallOption) (*DocxTemplate, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DocxTemplate)
	err := c.cc.Invoke(ctx, DocxTemplateService_GetSingleDocxTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *docxTemplateServiceClient) UpdateDocxTemplate(ctx context.Context, in *UpdateDocxTemplateReq, opts ...grpc.CallOption) (*DocxTemplate, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DocxTemplate)
	err := c.cc.Invoke(ctx, DocxTemplateService_UpdateDocxTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *docxTemplateServiceClient) DeleteDocxTemplate(ctx context.Context, in *DeleteDocxTemplateReq, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, DocxTemplateService_DeleteDocxTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DocxTemplateServiceServer is the server API for DocxTemplateService service.
// All implementations must embed UnimplementedDocxTemplateServiceServer
// for forward compatibility.
type DocxTemplateServiceServer interface {
	CreateDocxTemplate(context.Context, *CreateDocxTemplateReq) (*DocxTemplate, error)
	GetListDocxTemplate(context.Context, *GetListDocxTemplateReq) (*GetListDocxTemplateRes, error)
	GetSingleDocxTemplate(context.Context, *GetSingleDocxTemplateReq) (*DocxTemplate, error)
	UpdateDocxTemplate(context.Context, *UpdateDocxTemplateReq) (*DocxTemplate, error)
	DeleteDocxTemplate(context.Context, *DeleteDocxTemplateReq) (*empty.Empty, error)
	mustEmbedUnimplementedDocxTemplateServiceServer()
}

// UnimplementedDocxTemplateServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDocxTemplateServiceServer struct{}

func (UnimplementedDocxTemplateServiceServer) CreateDocxTemplate(context.Context, *CreateDocxTemplateReq) (*DocxTemplate, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDocxTemplate not implemented")
}
func (UnimplementedDocxTemplateServiceServer) GetListDocxTemplate(context.Context, *GetListDocxTemplateReq) (*GetListDocxTemplateRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetListDocxTemplate not implemented")
}
func (UnimplementedDocxTemplateServiceServer) GetSingleDocxTemplate(context.Context, *GetSingleDocxTemplateReq) (*DocxTemplate, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSingleDocxTemplate not implemented")
}
func (UnimplementedDocxTemplateServiceServer) UpdateDocxTemplate(context.Context, *UpdateDocxTemplateReq) (*DocxTemplate, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDocxTemplate not implemented")
}
func (UnimplementedDocxTemplateServiceServer) DeleteDocxTemplate(context.Context, *DeleteDocxTemplateReq) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDocxTemplate not implemented")
}
func (UnimplementedDocxTemplateServiceServer) mustEmbedUnimplementedDocxTemplateServiceServer() {}
func (UnimplementedDocxTemplateServiceServer) testEmbeddedByValue()                             {}

// UnsafeDocxTemplateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DocxTemplateServiceServer will
// result in compilation errors.
type UnsafeDocxTemplateServiceServer interface {
	mustEmbedUnimplementedDocxTemplateServiceServer()
}

func RegisterDocxTemplateServiceServer(s grpc.ServiceRegistrar, srv DocxTemplateServiceServer) {
	// If the following call pancis, it indicates UnimplementedDocxTemplateServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DocxTemplateService_ServiceDesc, srv)
}

func _DocxTemplateService_CreateDocxTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDocxTemplateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocxTemplateServiceServer).CreateDocxTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocxTemplateService_CreateDocxTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocxTemplateServiceServer).CreateDocxTemplate(ctx, req.(*CreateDocxTemplateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocxTemplateService_GetListDocxTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListDocxTemplateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocxTemplateServiceServer).GetListDocxTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocxTemplateService_GetListDocxTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocxTemplateServiceServer).GetListDocxTemplate(ctx, req.(*GetListDocxTemplateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocxTemplateService_GetSingleDocxTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSingleDocxTemplateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocxTemplateServiceServer).GetSingleDocxTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocxTemplateService_GetSingleDocxTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocxTemplateServiceServer).GetSingleDocxTemplate(ctx, req.(*GetSingleDocxTemplateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocxTemplateService_UpdateDocxTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDocxTemplateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocxTemplateServiceServer).UpdateDocxTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocxTemplateService_UpdateDocxTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocxTemplateServiceServer).UpdateDocxTemplate(ctx, req.(*UpdateDocxTemplateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocxTemplateService_DeleteDocxTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDocxTemplateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocxTemplateServiceServer).DeleteDocxTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocxTemplateService_DeleteDocxTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocxTemplateServiceServer).DeleteDocxTemplate(ctx, req.(*DeleteDocxTemplateReq))
	}
	return interceptor(ctx, in, info, handler)
}

// DocxTemplateService_ServiceDesc is the grpc.ServiceDesc for DocxTemplateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DocxTemplateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "docx_template_service.DocxTemplateService",
	HandlerType: (*DocxTemplateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDocxTemplate",
			Handler:    _DocxTemplateService_CreateDocxTemplate_Handler,
		},
		{
			MethodName: "GetListDocxTemplate",
			Handler:    _DocxTemplateService_GetListDocxTemplate_Handler,
		},
		{
			MethodName: "GetSingleDocxTemplate",
			Handler:    _DocxTemplateService_GetSingleDocxTemplate_Handler,
		},
		{
			MethodName: "UpdateDocxTemplate",
			Handler:    _DocxTemplateService_UpdateDocxTemplate_Handler,
		},
		{
			MethodName: "DeleteDocxTemplate",
			Handler:    _DocxTemplateService_DeleteDocxTemplate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "docx_template.proto",
}
