CREATE TYPE category_type AS ENUM (
    'Menu',
    'Profile Setting',
    'Setting',
    'Table',
    'Permission',
    'Resource',
    'API keys',
    'Custom endpoint',
    'UserInvite',
    'Fuctions',
    'Activity Logs',
    'Layout',
    'Fields',
    'Field settings',
    'Field type',
    'Relation',
    'Action',
    'Custom error',
    'Calendar view',
    'Microfrontend',
    'LoginPage'
);

ALTER TABLE "language"
ADD COLUMN "category" category_type NOT NULL DEFAULT 'Menu',
ADD COLUMN "platform" VARCHAR(100) DEFAULT 'Admin' NOT NULL;

INSERT INTO "language" ("key", "translations", "category", "platform") VALUES
('Settings', '{"uz": "Sozlamalar", "ru": "Настройки", "en": "Settings"}', 'Menu', 'Admin'),
('Users', '{"uz": "Foydanaluvchilar", "ru": "Участники", "en": "Users"}', 'Menu', 'Admin'),
('Create', '{"uz": "Yaratish", "ru": "Создать", "en": "Create"}', 'Menu', 'Admin'),
('Files', '{"uz": "Fayllar", "ru": "Файлы", "en": "Files"}', 'Menu', 'Admin'),
('Languages', '{"uz": "Tillar", "ru": "Языки", "en": "Languages"}', 'Profile Setting', 'Admin'),
('Logout', '{"uz": "Chiqish", "ru": "Выход", "en": "Logout"}', 'Profile Setting', 'Admin'),
('Project Settings', '{"uz": "Loyiha Parametrlari", "ru": "Параметры Проекта", "en": "Project Settings"}', 'Setting', 'Admin'),
('Permissions', '{"uz": "Ruxsatlar", "ru": "Разрешение", "en": "Permissions"}', 'Setting', 'Admin'),
('Resources', '{"uz": "Resurslar", "ru": "Ресурсы", "en": "Resources"}', 'Setting', 'Admin'),
('Code', '{"uz": "Kod", "ru": "Код", "en": "Code"}', 'Setting', 'Admin'),
('Activity Logs', '{"uz": "Faoliyat Jurnallari", "ru": "Журналы Aктивности", "en": "Activity Logs"}', 'Setting', 'Admin'),
('Environments', '{"uz": "Chqish", "ru": "Выйти", "en": "Environments"}', 'Setting', 'Admin'),
('Versions', '{"uz": "Versiyalar", "ru": "Версии", "en": "Versions"}', 'Setting', 'Admin'),
('Language Control', '{"uz": "Tilni Boshqarish", "ru": "Языковой контроль", "en": "Language Control"}', 'Setting', 'Admin'),
('Functions', '{"uz": "Funksiyalar", "ru": "Функции", "en": "Functions"}', 'Setting', 'Admin'),
('Microfrontend', '{"uz": "Microfrontend", "ru": "Микрофронт", "en": "Microfrontend"}', 'Setting', 'Admin'),
('Upload ERD', '{"uz": "ERD Yuklash", "ru": "Загрузка ERD", "en": "Upload ERD"}', 'Setting', 'Admin'),
('Data', '{"uz": "Ma''lumotlar", "ru": "Данные", "en": "Data"}', 'Setting', 'Admin'),
('Models', '{"uz": "Modellar", "ru": "Модели", "en": "Models"}', 'Setting', 'Admin'),
('Name', '{"uz": "Ism", "ru": "Name", "en": "Name"}', 'Setting', 'Admin'),
('Language', '{"uz": "Til", "ru": "Язык", "en": "Language"}', 'Setting', 'Admin'),
('Currency', '{"uz": "Valyuta", "ru": "Валюта", "en": "Currency"}', 'Setting', 'Admin'),
('Timezone', '{"uz": "Vaqt Mintaqasi", "ru": "Часовой Пояс", "en": "Timezone"}', 'Setting', 'Admin'),
('Description', '{"uz": "Tavsif", "ru": "Описание", "en": "Description"}', 'Setting', 'Admin'),
('Add', '{"uz": "Qoshish", "ru": "Добавить", "en": "Add"}', 'Setting', 'Admin'),
('Create folder', '{"uz": "Papka Q oshish", "ru": "Создать Папку", "en": "Create folder"}', 'Menu', 'Admin'),
('Title', '{"uz": "Sarlavha", "ru": "Заголовок", "en": "Title"}', 'Table', 'Admin'),
('Default page link', '{"uz": "Standart sahifa havolasi", "ru": "Ссылка на страницу по умолчанию", "en": "Default page link"}', 'Table', 'Admin'),
('Self recover', '{"uz": "O‘zini Tiklash", "ru": "Самовосстановление", "en": "Self recover"}', 'Setting', 'Admin'),
('Self register', '{"uz": "Mustaqil Ro‘yxatdan O‘tish", "ru": "Самостоятельная Регистрация", "en": "Self register"}', 'Setting', 'Admin'),
('Table', '{"uz": "Jadval", "ru": "Таблица", "en": "Table"}', 'Setting', 'Admin'),
('Session limit', '{"uz": "Sessiya Kheklovi", "ru": "Лимит Сессии", "en": "Session limit"}', 'Setting', 'Admin'),
('Matrix Details', '{"uz": "Matritsa Tafsilotlari", "ru": "Детали Mатрицы", "en": "Matrix Details"}', 'Setting', 'Admin'),
('Role', '{"uz": "Rol", "ru": "Роль", "en": "Role"}', 'Setting', 'Admin'),
('Connection', '{"uz": "Ulanish", "ru": "Соединение", "en": "Connection"}', 'Setting', 'Admin'),
('View slug', '{"uz": "Slugni Ko‘rish", "ru": "Просмотр Слага", "en": "View slug"}', 'Setting', 'Admin'),
('Table slug', '{"uz": "Jadval slugi", "ru": "Слаг Таблицы", "en": "Table slug"}', 'Setting', 'Admin'),
('Table', '{"uz": "Jadval", "ru": "Таблица", "en": "Table"}', 'Permission', 'Admin'),
('Menu', '{"uz": "Menyu", "ru": "Меню", "en": "Menu"}', 'Permission', 'Admin'),
('Global Permission', '{"uz": "Global Ruxsat", "ru": "Глобальное Pазрешение", "en": "Global Permission"}', 'Permission', 'Admin'),
('Objects', '{"uz": "Obyektlar", "ru": "Объекты", "en": "Objects"}', 'Permission', 'Admin'),
('Record Permission', '{"uz": "Yozish ruxsatnomasi", "ru": "Разрешение на запись", "en": "Record Permission"}', 'Permission', 'Admin'),
('Field Permission', '{"uz": "Maydon uchun ruxsat", "ru": "Разрешение на поле", "en": "Field Permission"}', 'Permission', 'Admin'),
('Action Permission', '{"uz": "Amal uchun ruxsat", "ru": "Разрешение на действие", "en": "Action Permission"}', 'Permission', 'Admin'),
('Relation Permission', '{"uz": "Aloqa uchun ruxsat", "ru": "Разрешение на связь", "en": "Relation Permission"}', 'Permission', 'Admin'),
('View Permission', '{"uz": "Ko‘rish uchun ruxsat", "ru": "Разрешение на просмотр", "en": "View Permission"}', 'Permission', 'Admin'),
('Custom Permission', '{"uz": "Maxsus ruxsat", "ru": "Пользовательское разрешение", "en": "Custom Permission"}', 'Permission', 'Admin'),
('Reading', '{"uz": "O‘qish", "ru": "Чтение", "en": "Reading"}', 'Permission', 'Admin'),
('Adding', '{"uz": "Qo‘shish", "ru": "Добавление", "en": "Adding"}', 'Permission', 'Admin'),
('Editing', '{"uz": "Tahrirlash", "ru": "Редактирование", "en": "Editing"}', 'Permission', 'Admin'),
('Deleting', '{"uz": "O‘chirish", "ru": "Удаление", "en": "Deleting"}', 'Permission', 'Admin'),
('Public', '{"uz": "Ommaviy", "ru": "Публичный", "en": "Public"}', 'Permission', 'Admin'),
('Resource settings', '{"uz": "Resurs sozlamalari", "ru": "Настройки ресурса", "en": "Resource settings"}', 'Setting', 'Admin'),
('API keys', '{"uz": "API Kalitlari", "ru": "Ключи API", "en": "API keys"}', 'Setting', 'Admin'),
('Redirects', '{"uz": "Yo‘naltirishlar", "ru": "Перенаправления", "en": "Redirects"}', 'Custom endpoint', 'Admin'),
('From', '{"uz": "Dan", "ru": "Из", "en": "From"}', 'Custom endpoint', 'Admin'),
('Created at', '{"uz": "Yaratilgan vaqti", "ru": "Создано в", "en": "Created at"}', 'Custom endpoint', 'Admin'),
('Updated at', '{"uz": "Yangilangan vaqti", "ru": "Обновлено в", "en": "Updated at"}', 'Custom endpoint', 'Admin'),
('Create new', '{"uz": "Yangi yaratish", "ru": "Создать новый", "en": "Create new"}', 'Setting', 'Admin'),
('Faas functions', '{"uz": "FaaS funksiyalari", "ru": "Функции FaaS", "en": "Faas functions"}', 'Fuctions', 'Admin'),
('Status', '{"uz": "Statuslar", "ru": "Статус", "en": "Status"}', 'Fuctions', 'Admin'),
('Path', '{"uz": "Yo‘l", "ru": "Путь", "en": "Path"}', 'Fuctions', 'Admin'),
('Microfrontend', '{"uz": "Mikrofrontend", "ru": "Микрофронтенд", "en": "Microfrontend"}', 'Setting', 'Admin'),
('Link', '{"uz": "Havola", "ru": "Ссылка", "en": "Link"}', 'Microfrontend', 'Admin'),
('Framework type', '{"uz": "Freymvork turi", "ru": "Тип фреймворка", "en": "Framework type"}', 'Microfrontend', 'Admin'),
('Activity Logs', '{"uz": "Faoliyat jurnallari", "ru": "Журналы активности", "en": "Activity Logs"}', 'Setting', 'Admin'),
('Action', '{"uz": "Amal", "ru": "Действие", "en": "Action"}', 'Activity Logs', 'Admin'),
('Collection', '{"uz": "To‘plam", "ru": "Коллекция", "en": "Collection"}', 'Activity Logs', 'Admin'),
('Action On', '{"uz": "Amal bajariladigan obyekt", "ru": "Действие на", "en": "Action On"}', 'Activity Logs', 'Admin'),
('Action By', '{"uz": "Amal bajargan shaxs", "ru": "Действие выполнено", "en": "Action By"}', 'Activity Logs', 'Admin'),
('Media', '{"uz": "Media", "ru": "Медиа", "en": "Media"}', 'Menu', 'Admin'),
('Items', '{"uz": "Elementlar", "ru": "Элементы", "en": "Items"}', 'Table', 'Admin'),
('Select All', '{"uz": "Barchasini tanlash", "ru": "Выбрать все", "en": "Select All"}', 'Table', 'Admin'),
('Name', '{"uz": "Nomi", "ru": "Наименование", "en": "Name"}', 'Table', 'Admin'),
('Login', '{"uz": "Kirish", "ru": "Вход", "en": "Login"}', 'LoginPage', 'Admin'),
('Mail', '{"uz": "Pochta", "ru": "Почта", "en": "Mail"}', 'UserInvite', 'Admin'),
('Phone', '{"uz": "Telefon", "ru": "Телефон", "en": "Phone"}', 'UserInvite', 'Admin'),
('Invite', '{"uz": "Taklif qilish", "ru": "Пригласить", "en": "Invite"}', 'UserInvite', 'Admin'),
('Show', '{"uz": "Ko‘rsatish", "ru": "Показать", "en": "Show"}', 'Menu', 'Admin'),
('Invite user', '{"uz": "Foydalanuvchini taklif qilish", "ru": "Пригласить пользователя", "en": "Invite user"}', 'UserInvite', 'Admin'),
('Password', '{"uz": "Parol", "ru": "Пароль", "en": "Password"}', 'UserInvite', 'Admin'),
('User type', '{"uz": "Foydalanuvchi turi", "ru": "Тип пользователя", "en": "User type"}', 'UserInvite', 'Admin'),
('More', '{"uz": "Ko‘proq", "ru": "Еще", "en": "More"}', 'UserInvite', 'Admin'),
('Email', '{"uz": "Pochta", "ru": "Электронная почта", "en": "Email"}', 'UserInvite', 'Admin'),
('Active role', '{"uz": "Faol rol", "ru": "Активная роль", "en": "Active role"}', 'UserInvite', 'Admin'),
('Create table', '{"uz": "Jadval yaratish", "ru": "Создать таблицу", "en": "Create table"}', 'Menu', 'Admin'),
('Add table', '{"uz": "Jadval qo‘shish", "ru": "Добавить таблицу", "en": "Add table"}', 'Menu', 'Admin'),
('Add microfrontend', '{"uz": "Mikrofrontend qo‘shish", "ru": "Добавить микрофронтенд", "en": "Add microfrontend"}', 'Menu', 'Admin'),
('Add website', '{"uz": "Veb-sayt qo‘shish", "ru": "Добавить сайт", "en": "Add website"}', 'Menu', 'Admin'),
('Add folder', '{"uz": "Добавить папку", "ru": "Jild qo‘shish", "en": "Add folder"}', 'Menu', 'Admin'),
('General', '{"uz": "Umumiy", "ru": "Общий", "en": "General"}', 'Table', 'Admin'),
('Key', '{"uz": "Kalit", "ru": "Ключ", "en": "Key"}', 'Table', 'Admin'),
('Login table', '{"uz": "Kirish jadvali", "ru": "Таблица входа", "en": "Login table"}', 'Table', 'Admin'),
('Cache', '{"uz": "Kesh", "ru": "Кэш", "en": "Cache"}', 'Table', 'Admin'),
('Soft delete', '{"uz": "Yengil o‘chirish", "ru": "Мягкое удаление", "en": "Soft delete"}', 'Table', 'Admin'),
('Sort', '{"uz": "Saralash", "ru": "Сортировка", "en": "Sort"}', 'Table', 'Admin'),
('Attach to table', '{"uz": "Jadvalga ulash", "ru": "Прикрепить к таблице", "en": "Attach to table"}', 'Menu', 'Admin'),
('Attach to microfrontend', '{"uz": "Mikrofrontendga ulash", "ru": "Прикрепить к микрофронтенду", "en": "Attach to microfrontend"}', 'Menu', 'Admin'),
('Add params', '{"uz": "Parametrlarni qo‘shish", "ru": "Добавить параметры", "en": "Add params"}', 'Menu', 'Admin'),
('Website Link', '{"uz": "Veb-sayt havolasi", "ru": "Ссылка на сайт", "en": "Website Link"}', 'Menu', 'Admin'),
('Save', '{"uz": "Saqlash", "ru": "Сохранить", "en": "Save"}', 'Menu', 'Admin'),
('View', '{"uz": "Ko‘rish", "ru": "Просмотр", "en": "View"}', 'Table', 'Admin'),
('Create item', '{"uz": "Element yaratish", "ru": "Создать элемент", "en": "Create item"}', 'Table', 'Admin'),
('Search', '{"uz": "Qidirish", "ru": "Поиск", "en": "Search"}', 'Table', 'Admin'),
('Details', '{"uz": "Tafsilotlar", "ru": "Детали", "en": "Details"}', 'Table', 'Admin'),
('Fields', '{"uz": "Maydonlar", "ru": "Поля", "en": "Fields"}', 'Table', 'Admin'),
('Relations', '{"uz": "Aloqalar", "ru": "Связи", "en": "Relations"}', 'Table', 'Admin'),
('Actions', '{"uz": "Amallar", "ru": "Действия", "en": "Actions"}', 'Table', 'Admin'),
('Custom errors', '{"uz": "Maxsus xatoliklar", "ru": "Пользовательские ошибки", "en": "Custom errors"}', 'Table', 'Admin'),
('Default', '{"uz": "Standart", "ru": "По умолчанию", "en": "Default"}', 'Layout', 'Admin'),
('Modal', '{"uz": "Modal oynasi", "ru": "Модальное окно", "en": "Modal"}', 'Layout', 'Admin'),
('Remove tabs', '{"uz": "Tablarni olib tashlash", "ru": "Удалить вкладки", "en": "Remove tabs"}', 'Layout', 'Admin'),
('Field Label', '{"uz": "Maydon yorligi", "ru": "Метка поля", "en": "Field Label"}', 'Fields', 'Admin'),
('Field Type', '{"uz": "Maydon turi", "ru": "Тип поля", "en": "Field Type"}', 'Fields', 'Admin'),
('Field Slug', '{"uz": "Maydon slugi", "ru": "Слаг поля", "en": "Field Slug"}', 'Fields', 'Admin'),
('Table from', '{"uz": "Jadvaldan", "ru": "Таблица из", "en": "Table from"}', 'Relation', 'Admin'),
('Table to', '{"uz": "Jadvalga", "ru": "Таблица в", "en": "Table to"}', 'Relation', 'Admin'),
('Relation type', '{"uz": "Aloqa turi", "ru": "Тип связи", "en": "Relation type"}', 'Relation', 'Admin'),
('Action type', '{"uz": "Amal turi", "ru": "Тип действия", "en": "Action type"}', 'Action', 'Admin'),
('Message', '{"uz": "Xabar", "ru": "Сообщение", "en": "Message"}', 'Custom error', 'Admin'),
('Field create', '{"uz": "Maydon yaratish", "ru": "Создать поле", "en": "Field create"}', 'Fields', 'Admin'),
('Default value', '{"uz": "Standart qiymat", "ru": "Значение по умолчанию", "en": "Default value"}', 'Field settings', 'Admin'),
('Schema', '{"uz": "Skhema", "ru": "Схема", "en": "Schema"}', 'Field settings', 'Admin'),
('Validation', '{"uz": "Tekshiruv", "ru": "Валидизация", "en": "Validation"}', 'Field settings', 'Admin'),
('Autofill', '{"uz": "Avto to‘ldirish", "ru": "Автозаполнение", "en": "Autofill"}', 'Field settings', 'Admin'),
('Auto filter', '{"uz": "Avto filtrlash", "ru": "Автофильтр", "en": "Auto filter"}', 'Field settings', 'Admin'),
('Field hide', '{"uz": "Maydonni yashirish", "ru": "Скрыть поле", "en": "Field hide"}', 'Field settings', 'Admin'),
('Error message', '{"uz": "Xatolik xabari", "ru": "Сообщение об ошибке", "en": "Error message"}', 'Field settings', 'Admin'),
('Disabled', '{"uz": "O‘chirilgan", "ru": "Отключено", "en": "Disabled"}', 'Field settings', 'Admin'),
('Required', '{"uz": "Majburiy", "ru": "Обязательно", "en": "Required"}', 'Field settings', 'Admin'),
('Duplicate', '{"uz": "Takrorlash", "ru": "Дубликат", "en": "Duplicate"}', 'Field settings', 'Admin'),
('Autofill table', '{"uz": "Jadvalni avto-to‘ldirish", "ru": "Автозаполнение таблицы", "en": "Autofill table"}', 'Field settings', 'Admin'),
('Autofilter field', '{"uz": "Maydonni avto-filtrlash", "ru": "Автофильтр поля", "en": "Autofilter field"}', 'Field settings', 'Admin'),
('Automatic', '{"uz": "Avtomatik", "ru": "Автоматический", "en": "Automatic"}', 'Field settings', 'Admin'),
('Hide field from', '{"uz": "Maydonni yashirish", "ru": "Скрыть поле от", "en": "Hide field from"}', 'Field settings', 'Admin'),
('Single Line', '{"uz": "Bir satrli tekst", "ru": "Одна строка", "en": "Single Line"}', 'Field type', 'Admin'),
('Multi Line', '{"uz": "Ko‘p satr", "ru": "Множественные строки", "en": "Multi Line"}', 'Field type', 'Admin'),
('Date', '{"uz": "Sana", "ru": "Дата", "en": "Date"}', 'Field type', 'Admin'),
('Date time', '{"uz": "Sana va vaqt", "ru": "Дата и время", "en": "Date time"}', 'Field type', 'Admin'),
('Date time - timezone', '{"uz": "Sana va vaqt - vaqt mintaqasi", "ru": "Дата и время - часовой пояс", "en": "Date time - timezone"}', 'Field type', 'Admin'),
('Time', '{"uz": "Vaqt", "ru": "Время", "en": "Time"}', 'Field type', 'Admin'),
('Number', '{"uz": "Raqam", "ru": "Число", "en": "Number"}', 'Field type', 'Admin'),
('Float', '{"uz": "O‘zgaruvchan nuqta soni", "ru": "Число с плавающей запятой", "en": "Float"}', 'Field type', 'Admin'),
('Money', '{"uz": "Pul", "ru": "Деньги", "en": "Money"}', 'Field type', 'Admin'),
('Checkbox', '{"uz": "Belgi Qutisi", "ru": "Флажок", "en": "Checkbox"}', 'Field type', 'Admin'),
('Switch', '{"uz": "O‘tkazgich", "ru": "Переключатель", "en": "Switch"}', 'Field type', 'Admin'),
('Select', '{"uz": "Tanlash", "ru": "Выбрать", "en": "Select"}', 'Field type', 'Admin'),
('Status', '{"uz": "Holat", "ru": "Статус", "en": "Status"}', 'Field type', 'Admin'),
('Point', '{"uz": "Nuqta", "ru": "Точка", "en": "Point"}', 'Field type', 'Admin'),
('Geozone', '{"uz": "Geozona", "ru": "Геозона", "en": "Geozone"}', 'Field type', 'Admin'),
('Photo', '{"uz": "Foto", "ru": "Фото", "en": "Photo"}', 'Field type', 'Admin'),
('Multi Image', '{"uz": "Ko‘p rasmlar", "ru": "Множественное изображение", "en": "Multi Image"}', 'Field type', 'Admin'),
('Video', '{"uz": "Video", "ru": "Видео", "en": "Video"}', 'Field type', 'Admin'),
('File', '{"uz": "Fayl", "ru": "Файл", "en": "File"}', 'Field type', 'Admin'),
('Formula', '{"uz": "Formula", "ru": "Формула", "en": "Formula"}', 'Field type', 'Admin'),
('Formula in frontend', '{"uz": "Frontendda formula", "ru": "Формула во фронтенде", "en": "Formula in frontend"}', 'Field type', 'Admin'),
('Formula in backend', '{"uz": "Backendda formula", "ru": "Формула в бэкенде", "en": "Formula in backend"}', 'Field type', 'Admin'),
('Text', '{"uz": "Matn", "ru": "Текст", "en": "Text"}', 'Field type', 'Admin'),
('Link', '{"uz": "Havola", "ru": "Ссылка", "en": "Link"}', 'Field type', 'Admin'),
('Person', '{"uz": "Odam", "ru": "Человек", "en": "Person"}', 'Field type', 'Admin'),
('Button', '{"uz": "Tugma", "ru": "Кнопка", "en": "Button"}', 'Field type', 'Admin'),
('Incremenet ID', '{"uz": "IDni oshirish", "ru": "Инкремент ID", "en": "Incremenet ID"}', 'Field type', 'Admin'),
('Internation phone', '{"uz": "Xalqaro telefon", "ru": "Международный телефон", "en": "Internation phone"}', 'Field type', 'Admin'),
('Email', '{"uz": "Pochta", "ru": "Почта", "en": "Email"}', 'Field type', 'Admin'),
('Icon', '{"uz": "Belgi", "ru": "Значок", "en": "Icon"}', 'Field type', 'Admin'),
('Password', '{"uz": "Parol", "ru": "Пароль", "en": "Password"}', 'Field type', 'Admin'),
('Color', '{"uz": "Rang", "ru": "Цвет", "en": "Color"}', 'Field type', 'Admin'),
('View fields', '{"uz": "Ko‘rish maydonlari", "ru": "Поля просмотра", "en": "View fields"}', 'Table', 'Admin'),
('Disable Edit table', '{"uz": "Tahrir qilish jadvalini o‘chirib qo‘yish", "ru": "Отключить редактирование таблицы", "en": "Disable Edit table"}', 'Table', 'Admin'),
('Enable Multi language', '{"uz": "Ko‘p tillilikni yoqish", "ru": "Включить многоязычность", "en": "Enable Multi language"}', 'Table', 'Admin'),
('Additional', '{"uz": "Qo‘shimcha", "ru": "Дополнительный", "en": "Additional"}', 'Table', 'Admin'),
('Default editable', '{"uz": "Standart tahrirlanadigan", "ru": "Редактируемый по умолчанию", "en": "Default editable"}', 'Table', 'Admin'),
('Creatable', '{"uz": "Yaratish mumkin bo‘lgan", "ru": "Создаваемый", "en": "Creatable"}', 'Permission', 'Admin'),
('Relation Buttons', '{"uz": "Aloqa tugmalari", "ru": "Кнопки отношения", "en": "Relation Buttons"}', 'Permission', 'Admin'),
('Create relation', '{"uz": "Aloqa yaratish", "ru": "Создать связь", "en": "Create relation"}', 'Permission', 'Admin'),
('Redirect URL', '{"uz": "URL ni yoʻnaltirish", "ru": "Перенаправить URL", "en": "Redirect URL"}', 'Action', 'Admin'),
('Action type', '{"uz": "Harakat turi", "ru": "Тип действия", "en": "Action type"}', 'Action', 'Admin'),
('Method', '{"uz": "Usul", "ru": "Метод", "en": "Method"}', 'Action', 'Admin'),
('No limit', '{"uz": "Cheklov yo‘q", "ru": "Без ограничений", "en": "No limit"}', 'Action', 'Admin'),
('Fields list', '{"uz": "Maydonlar roʻyxati", "ru": "Список полей", "en": "Fields list"}', 'Custom error', 'Admin'),
('Error id', '{"uz": "Xato ID", "ru": "ID ошибки", "en": "Error id"}', 'Custom error', 'Admin'),
('Add fields', '{"uz": "Maydonlarni qo''shish", "ru": "Добавить поля", "en": "Add fields"}', 'Table', 'Admin'),
('Form fields', '{"uz": "Shakl maydonlari", "ru": "Поля формы", "en": "Form fields"}', 'Layout', 'Admin'),
('Relation tabs', '{"uz": "Aloqa yorliqlari", "ru": "Вкладки отношений", "en": "Relation tabs"}', 'Layout', 'Admin'),
('Section tabs', '{"uz": "Bo''lim yorliqlari", "ru": "Вкладки разделов", "en": "Section tabs"}', 'Layout', 'Admin'),
('Relation table', '{"uz": "Aloqa jadvali", "ru": "Таблица отношений", "en": "Relation table"}', 'Layout', 'Admin'),
('Add section tab', '{"uz": "Bo''lim yorlig''ini qo''shish", "ru": "Добавить вкладку раздела", "en": "Add section tab"}', 'Layout', 'Admin'),
('Add section', '{"uz": "Bo''lim qo''shish", "ru": "Добавить раздел", "en": "Add section"}', 'Layout', 'Admin'),
('View options', '{"uz": "Ko‘rish parametrlari", "ru": "Параметры отображения", "en": "View options"}', 'Layout', 'Admin'),
('Layout', '{"uz": "Maket", "ru": "Макет", "en": "Layout"}', 'Table', 'Admin'),
('Columns', '{"uz": "Ustunlar", "ru": "Столбцы", "en": "Columns"}', 'Table', 'Admin'),
('Group', '{"uz": "Guruh", "ru": "Группа", "en": "Group"}', 'Table', 'Admin'),
('Tab group', '{"uz": "Yorliq guruhi", "ru": "Группа вкладок", "en": "Tab group"}', 'Table', 'Admin'),
('Fix column', '{"uz": "Ustunni mustahkamlash", "ru": "Закрепить столбец", "en": "Fix column"}', 'Table', 'Admin'),
('Export', '{"uz": "Eksport", "ru": "Экспорт", "en": "Export"}', 'Table', 'Admin'),
('Import', '{"uz": "Import", "ru": "Импорт", "en": "Import"}', 'Table', 'Admin'),
('Delete', '{"uz": "O‘chirish", "ru": "Удалить", "en": "Delete"}', 'Table', 'Admin'),
('Docs', '{"uz": "Hujjatlar", "ru": "Документы", "en": "Docs"}', 'Table', 'Admin'),
('Visible columns', '{"uz": "Ko‘rinadigan ustunlar", "ru": "Видимые столбцы", "en": "Visible columns"}', 'Table', 'Admin'),
('Seaarch by filled name', '{"uz": "To‘ldirilgan nom bo‘yicha qidirish", "ru": "Поиск по заполненному имени", "en": "Search by filled name"}', 'Table', 'Admin'),
('Show all', '{"uz": "Hammasini ko‘rsatish", "ru": "Показать все", "en": "Show all"}', 'Table', 'Admin'),
('Group columns', '{"uz": "Ustunlarni guruhlash", "ru": "Группировка столбцов", "en": "Group columns"}', 'Table', 'Admin'),
('Tab group columns', '{"uz": "Yorliq guruhining ustunlari", "ru": "Столбцы группы вкладок", "en": "Tab group columns"}', 'Table', 'Admin'),
('Fix columns', '{"uz": "Ustunlarni mustahkamlash", "ru": "Закрепить столбцы", "en": "Fix columns"}', 'Table', 'Admin'),
('Upload file', '{"uz": "Fayl yuklash", "ru": "Загрузить файл", "en": "Upload file"}', 'Table', 'Admin'),
('Confirmation', '{"uz": "Tasdiqlash", "ru": "Подтверждение", "en": "Confirmation"}', 'Table', 'Admin'),
('Drag and drop files here', '{"uz": "Fayllarni bu yerga olib kelib qo‘ying", "ru": "Перетащите файлы сюда", "en": "Drag and drop files here"}', 'Table', 'Admin'),
('Browse', '{"uz": "Ko‘rish", "ru": "Обзор", "en": "Browse"}', 'Calendar view', 'Admin'),
('Today', '{"uz": "Bugun", "ru": "Сегодня", "en": "Today"}', 'Calendar view', 'Admin'),
('Day', '{"uz": "Kun", "ru": "День", "en": "Day"}', 'Calendar view', 'Admin'),
('Calendar settings', '{"uz": "Taqvim sozlamalari", "ru": "Настройки календаря", "en": "Calendar settings"}', 'Calendar view', 'Admin'),
('Time from', '{"uz": "Vaqtdan boshlab", "ru": "Время с", "en": "Time from"}', 'Calendar view', 'Admin'),
('Time to', '{"uz": "Vaqtga qadar", "ru": "Время до", "en": "Time to"}', 'Calendar view', 'Admin'),
('Edit field', '{"uz": "Maydonni tahrirlash", "ru": "Редактировать поле", "en": "Edit field"}', 'Table', 'Admin'),
('Sort A -> Z', '{"uz": "Saralash A -> Z", "ru": "Сортировать A -> Z", "en": "Sort A -> Z"}', 'Table', 'Admin'),
('Add Summary', '{"uz": "Xulosa qo‘shish", "ru": "Добавить итог", "en": "Add Summary"}', 'Table', 'Admin'),
('Fix column', '{"uz": "Ustunni mustahkamlash", "ru": "Закрепить столбец", "en": "Fix column"}', 'Table', 'Admin'),
('Hide field', '{"uz": "Maydonni yashirish", "ru": "Скрыть поле", "en": "Hide field"}', 'Table', 'Admin'),
('Delete field', '{"uz": "Maydonni o‘chirish", "ru": "Удалить поле", "en": "Delete field"}', 'Table', 'Admin'),
('Log out of your account', '{"uz": "Hisobingizdan chiqish", "ru": "Выйти из аккаунта", "en": "Log out of your account"}', 'Profile Setting', 'Admin'),
('You will need to log back in to access your workspace.', '{"uz": "Ish maydoningizga kirish uchun qaytadan tizimga kirishingiz kerak bo‘ladi.", "ru": "Вам нужно будет снова войти, чтобы получить доступ к рабочему пространству.", "en": "You will need to log back in to access your workspace."}', 'Profile Setting', 'Admin'),
('Log out', '{"uz": "Chiqish", "ru": "Выйти", "en": "Log out"}', 'Profile Setting', 'Admin'),
('Cancel', '{"uz": "Bekor qilish", "ru": "Отменить", "en": "Cancel"}', 'Profile Setting', 'Admin'),
('Edit tables', '{"uz": "Jadvallarni tahrirlash", "ru": "Редактировать таблицы", "en": "Edit tables"}', 'Menu', 'Admin'),
('Delete table', '{"uz": "Jadvalni o''chirish", "ru": "Удалить таблицу", "en": "Delete table"}', 'Menu', 'Admin'),
('Add', '{"uz": "Qo‘shish", "ru": "Добавить", "en": "Add"}', 'Menu', 'Admin'),
('Custom endpoint', '{"uz": "Maxsus endpoint", "ru": "Пользовательская конечная точка", "en": "Custom endpoint"}', 'Setting', 'Admin'),
('Create Folder', '{"uz": "Papka yaratish", "ru": "Создать папку", "en": "Create Folder"}', 'Setting', 'Admin'),
('Default page link', '{"uz": "Standart sahifa havolasi", "ru": "Ссылка на страницу по умолчанию", "en": "Default page link"}', 'Setting', 'Admin'),
('Table', '{"uz": "Jadval", "ru": "Таблица", "en": "Table"}', 'Setting', 'Admin'),
('Name', '{"uz": "Nomi", "ru": "Название", "en": "Name"}', 'Setting', 'Admin'),
('Main table slug', '{"uz": "Asosiy jadval slagi", "ru": "Основной слаг таблицы", "en": "Main table slug"}', 'Setting', 'Admin'),
('Field slug', '{"uz": "Maydon slag", "ru": "Слаг поля", "en": "Field slug"}', 'Setting', 'Admin'),
('Create connection', '{"uz": "Ulanishni yaratish", "ru": "Создать соединение", "en": "Create cfonnection"}', 'Setting', 'Admin'),
('Edit connection', '{"uz": "Ulanishni tahrirlash", "ru": "Редактировать соединение", "en": "Edit connection"}', 'Setting', 'Admin'),
('Type', '{"uz": "Turi", "ru": "Тип", "en": "Type"}', 'Setting', 'Admin'),
('Resource Info', '{"uz": "Resurs ma''lumotlari", "ru": "Информация о ресурсе", "en": "Resource Info"}', 'Setting', 'Admin'),
('Save changes', '{"uz": "O''zgarishlarni saqlash", "ru": "Сохранить изменения", "en": "Save changes"}', 'Setting', 'Admin'),
('Reconnect', '{"uz": "Qayta ulanish", "ru": "Переподключиться", "en": "Reconnect"}', 'Setting', 'Admin'),
('All users', '{"uz": "Barcha foydalanuvchilar", "ru": "Все пользователи", "en": "All users"}', 'Setting', 'Admin'),
('Resources let you connect to your database or API. Once you add a resource here, you can use it in all your apps.', '{"uz": "Resurslar sizga ma''lumotlar bazangiz yoki API-ga ulanish imkonini beradi. Bir marta resursni qo''shsangiz, uni barcha ilovalaringizda ishlatishingiz mumkin.", "ru": "Ресурсы позволяют вам подключаться к вашей базе данных или API. После добавления ресурса вы можете использовать его во всех своих приложениях.", "en": "Resources let you connect to your database or API. Once you add a resource here, you can use it in all your apps."}', 'Setting', 'Admin'),
('Gitlab username', '{"uz": "Gitlab foydalanuvchi nomi", "ru": "Имя пользователя Gitlab", "en": "Gitlab username"}', 'Setting', 'Admin'),
('Token', '{"uz": "Token", "ru": "Токен", "en": "Token"}', 'Setting', 'Admin'),
('Allowlisting', '{"uz": "Ruxsat ro''yxati", "ru": "Белый список", "en": "Allowlisting"}', 'Setting', 'Admin'),
('Please allow us to connect to your database by allowing our IP addresses:', '{"uz": "Iltimos, bizga IP manzillarimizni ruxsat berish orqali ma''lumotlar bazangizga ulanishga ruxsat bering:", "ru": "Пожалуйста, разрешите нам подключиться к вашей базе данных, разрешив наши IP-адреса:", "en": "Please allow us to connect to your database by allowing our IP addresses:"}', 'Setting', 'Admin'),
('Resource info', '{"uz": "Resurs ma''lumotlari", "ru": "Информация о ресурсе", "en": "Resource info"}', 'Setting', 'Admin'),
('Resource name', '{"uz": "Resurs nomi", "ru": "Название ресурса", "en": "Resource name"}', 'Setting', 'Admin'),
('Save', '{"uz": "Saqlash", "ru": "Сохранить", "en": "Save"}', 'Setting', 'Admin'),
('Password', '{"uz": "Parol", "ru": "Пароль", "en": "Password"}', 'Setting', 'Admin'),
('Originator', '{"uz": "Yaratuvchi", "ru": "Создатель", "en": "Originator"}', 'Setting', 'Admin'),
('Number of Otp', '{"uz": "OTP soni", "ru": "Количество OTP", "en": "Number of OTP"}', 'Setting', 'Admin'),
('Used count', '{"uz": "Foydalanilgan soni", "ru": "Количество использований", "en": "Used count"}', 'Setting', 'Admin'),
('RPS limit', '{"uz": "RPS cheklovi", "ru": "Лимит RPS", "en": "RPS limit"}', 'Setting', 'Admin'),
('Monthly limit', '{"uz": "Oylik cheklov", "ru": "Месячный лимит", "en": "Monthly limit"}', 'Setting', 'Admin'),
('Platform name', '{"uz": "Platforma nomi", "ru": "Название платформы", "en": "Platform name"}', 'Setting', 'Admin'),
('Client ID', '{"uz": "Mijoz ID", "ru": "ID клиента", "en": "Client ID"}', 'Setting', 'Admin'),
('Download Api documentation', '{"uz": "API hujjatlarini yuklab olish", "ru": "Скачать документацию API", "en": "Download Api documentation"}', 'Setting', 'Admin'),
('Api keys', '{"uz": "API kalitlari", "ru": "API ключи", "en": "Api keys"}', 'Setting', 'Admin'),
('Host', '{"uz": "Xost", "ru": "Хост", "en": "Host"}', 'Setting', 'Admin'),
('Port', '{"uz": "Port", "ru": "Порт", "en": "Port"}', 'Setting', 'Admin'),
('Username', '{"uz": "Foydalanuvchi nomi", "ru": "Имя пользователя", "en": "Username"}', 'Setting', 'Admin'),
('Database', '{"uz": "Ma''lumotlar bazasi", "ru": "База данных", "en": "Database"}', 'Setting', 'Admin'),
('Default otp', '{"uz": "Standart OTP", "ru": "OTP по умолчанию", "en": "Default OTP"}', 'Setting', 'Admin'),
('Number of otp', '{"uz": "OTP soni", "ru": "Количество OTP", "en": "Number of OTP"}', 'Setting', 'Admin'),
('Variable Resource', '{"uz": "O''zgaruvchan resurs", "ru": "Переменный ресурс", "en": "Variable Resource"}', 'Setting', 'Admin'),
('Function type', '{"uz": "Funksiya turi", "ru": "Тип функции", "en": "Function type"}', 'Setting', 'Admin'),
('Link', '{"uz": "Havola", "ru": "Ссылка", "en": "Link"}', 'Setting', 'Admin'),
('Details', '{"uz": "Tafsilotlar", "ru": "Детали", "en": "Details"}', 'Fuctions', 'Admin'),
('Logs', '{"uz": "Jurnallar", "ru": "Логи", "en": "Logs"}', 'Fuctions', 'Admin'),
('Repository', '{"uz": "Repository", "ru": "Репозиторий", "en": "Repository"}', 'Fuctions', 'Admin'),
('Branch', '{"uz": "Filial", "ru": "Ветка", "en": "Branch"}', 'Fuctions', 'Admin'),
('Name', '{"uz": "Nomi", "ru": "Название", "en": "Name"}', 'Fuctions', 'Admin'),
('Description', '{"uz": "Tavsif", "ru": "Описание", "en": "Description"}', 'Fuctions', 'Admin'),
('Name', '{"uz": "Nomi", "ru": "Название", "en": "Name"}', 'Microfrontend', 'Admin'),
('Status', '{"uz": "Holati", "ru": "Статус", "en": "Status"}', 'Microfrontend', 'Admin'),
('Description', '{"uz": "Tavsif", "ru": "Описание", "en": "Description"}', 'Microfrontend', 'Admin'),
('Link', '{"uz": "Havola", "ru": "Ссылка", "en": "Link"}', 'Microfrontend', 'Admin'),
('Framework type', '{"uz": "Freyimvork turi", "ru": "Тип фреймворка", "en": "Framework type"}', 'Microfrontend', 'Admin'),
('Activity Logs', '{"uz": "Faoliyat jurnallari", "ru": "Журналы активности", "en": "Activity Logs"}', 'Activity Logs', 'Admin'),
('items', '{"uz": "Elementlar", "ru": "Элементы", "en": "Items"}', 'Activity Logs', 'Admin'),
('Count', '{"uz": "Soni", "ru": "Количество", "en": "Count"}', 'Activity Logs', 'Admin'),
('Save', '{"uz": "Saqlash", "ru": "Сохранить", "en": "Save"}', 'Activity Logs', 'Admin'),
('Role', '{"uz": "Roli", "ru": "Роль", "en": "Role"}', 'Activity Logs', 'Admin'),
('Edit User', '{"uz": "Foydalanuvchini tahrirlash", "ru": "Редактировать пользователя", "en": "Edit User"}', 'Activity Logs', 'Admin'),
('Sessions', '{"uz": "Sessiyalar", "ru": "Сессии", "en": "Sessions"}', 'Activity Logs', 'Admin'),
('Data', '{"uz": "Ma''lumotlar", "ru": "Данные", "en": "Data"}', 'Activity Logs', 'Admin'),
('Created time', '{"uz": "Yaratilgan vaqt", "ru": "Время создания", "en": "Created time"}', 'Activity Logs', 'Admin'),
('Search', '{"uz": "Qidiruv", "ru": "Поиск", "en": "Search"}', 'Table', 'Admin'),
('Add filter', '{"uz": "Filtr qo''shish", "ru": "Добавить фильтр", "en": "Add filter"}', 'Table', 'Admin'),
('View options', '{"uz": "Ko''rish variantlari", "ru": "Варианты просмотра", "en": "View options"}', 'Table', 'Admin'),
('Layout', '{"uz": "Tuzilishi", "ru": "Макет", "en": "Layout"}', 'Table', 'Admin'),
('Columns', '{"uz": "Ustunlar", "ru": "Колонки", "en": "Columns"}', 'Table', 'Admin'),
('Shown', '{"uz": "Ko''rsatilgan", "ru": "Показано", "en": "Shown"}', 'Table', 'Admin'),
('Tab Group', '{"uz": "Tab guruh", "ru": "Группа вкладок", "en": "Tab Group"}', 'Table', 'Admin'),
('Group', '{"uz": "Guruhlash", "ru": "Группировать", "en": "Group"}', 'Table', 'Admin'),
('Fixed', '{"uz": "Qattiq belgilangan", "ru": "Закреплено", "en": "Fixed"}', 'Table', 'Admin'),
('Visible columns', '{"uz": "Ko''rinadigan ustunlar", "ru": "Видимые колонки", "en": "Visible columns"}', 'Table', 'Admin'),
('Show all', '{"uz": "Hammasini ko''rsatish", "ru": "Показать все", "en": "Show all"}', 'Table', 'Admin'),
('Group Columns', '{"uz": "Ustunlarni guruhlash", "ru": "Группировка колонок", "en": "Group Columns"}', 'Table', 'Admin'),
('Search by filled name', '{"uz": "To''ldirilgan nom bo''yicha qidirish", "ru": "Поиск по заполненному имени", "en": "Search by filled name"}', 'Table', 'Admin');