ALTER TABLE "mcp_project"
    ADD COLUMN IF NOT EXISTS "ucode_project_id" UUID DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS "api_key" TEXT DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS "environment_id" UUID DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS "status" VARCHAR(20) DEFAULT NULL;
