ALTER TABLE IF EXISTS "menu"
    ADD COLUMN IF NOT EXISTS "view_id" UUID REFERENCES "view"("id") ON DELETE SET NULL;

ALTER TABLE IF EXISTS "view" 
    ADD COLUMN IF NOT EXISTS "table_id" UUID REFERENCES "table"("id") ON DELETE SET NULL,
    DROP COLUMN IF EXISTS "multiple_insert_field",
    DROP COLUMN IF EXISTS "main_field";

