// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: postgres_login.proto

package postgres_object_builder_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LoginService_Login_FullMethodName                    = "/postgres_object_builder_service.LoginService/Login"
	LoginService_LoginData_FullMethodName                = "/postgres_object_builder_service.LoginService/LoginData"
	LoginService_LoginWithOtp_FullMethodName             = "/postgres_object_builder_service.LoginService/LoginWithOtp"
	LoginService_LoginWithEmailOtp_FullMethodName        = "/postgres_object_builder_service.LoginService/LoginWithEmailOtp"
	LoginService_GetUserUpdatedPermission_FullMethodName = "/postgres_object_builder_service.LoginService/GetUserUpdatedPermission"
)

// LoginServiceClient is the client API for LoginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LoginServiceClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*V2LoginResponse, error)
	LoginData(ctx context.Context, in *LoginDataReq, opts ...grpc.CallOption) (*LoginDataRes, error)
	LoginWithOtp(ctx context.Context, in *PhoneOtpRequst, opts ...grpc.CallOption) (*V2LoginResponse, error)
	LoginWithEmailOtp(ctx context.Context, in *EmailOtpRequest, opts ...grpc.CallOption) (*V2LoginResponse, error)
	GetUserUpdatedPermission(ctx context.Context, in *GetUserUpdatedPermissionRequest, opts ...grpc.CallOption) (*V2LoginResponse, error)
}

type loginServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLoginServiceClient(cc grpc.ClientConnInterface) LoginServiceClient {
	return &loginServiceClient{cc}
}

func (c *loginServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*V2LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(V2LoginResponse)
	err := c.cc.Invoke(ctx, LoginService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginServiceClient) LoginData(ctx context.Context, in *LoginDataReq, opts ...grpc.CallOption) (*LoginDataRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginDataRes)
	err := c.cc.Invoke(ctx, LoginService_LoginData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginServiceClient) LoginWithOtp(ctx context.Context, in *PhoneOtpRequst, opts ...grpc.CallOption) (*V2LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(V2LoginResponse)
	err := c.cc.Invoke(ctx, LoginService_LoginWithOtp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginServiceClient) LoginWithEmailOtp(ctx context.Context, in *EmailOtpRequest, opts ...grpc.CallOption) (*V2LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(V2LoginResponse)
	err := c.cc.Invoke(ctx, LoginService_LoginWithEmailOtp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginServiceClient) GetUserUpdatedPermission(ctx context.Context, in *GetUserUpdatedPermissionRequest, opts ...grpc.CallOption) (*V2LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(V2LoginResponse)
	err := c.cc.Invoke(ctx, LoginService_GetUserUpdatedPermission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoginServiceServer is the server API for LoginService service.
// All implementations must embed UnimplementedLoginServiceServer
// for forward compatibility.
type LoginServiceServer interface {
	Login(context.Context, *LoginRequest) (*V2LoginResponse, error)
	LoginData(context.Context, *LoginDataReq) (*LoginDataRes, error)
	LoginWithOtp(context.Context, *PhoneOtpRequst) (*V2LoginResponse, error)
	LoginWithEmailOtp(context.Context, *EmailOtpRequest) (*V2LoginResponse, error)
	GetUserUpdatedPermission(context.Context, *GetUserUpdatedPermissionRequest) (*V2LoginResponse, error)
	mustEmbedUnimplementedLoginServiceServer()
}

// UnimplementedLoginServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLoginServiceServer struct{}

func (UnimplementedLoginServiceServer) Login(context.Context, *LoginRequest) (*V2LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedLoginServiceServer) LoginData(context.Context, *LoginDataReq) (*LoginDataRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginData not implemented")
}
func (UnimplementedLoginServiceServer) LoginWithOtp(context.Context, *PhoneOtpRequst) (*V2LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginWithOtp not implemented")
}
func (UnimplementedLoginServiceServer) LoginWithEmailOtp(context.Context, *EmailOtpRequest) (*V2LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginWithEmailOtp not implemented")
}
func (UnimplementedLoginServiceServer) GetUserUpdatedPermission(context.Context, *GetUserUpdatedPermissionRequest) (*V2LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserUpdatedPermission not implemented")
}
func (UnimplementedLoginServiceServer) mustEmbedUnimplementedLoginServiceServer() {}
func (UnimplementedLoginServiceServer) testEmbeddedByValue()                      {}

// UnsafeLoginServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LoginServiceServer will
// result in compilation errors.
type UnsafeLoginServiceServer interface {
	mustEmbedUnimplementedLoginServiceServer()
}

func RegisterLoginServiceServer(s grpc.ServiceRegistrar, srv LoginServiceServer) {
	// If the following call pancis, it indicates UnimplementedLoginServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LoginService_ServiceDesc, srv)
}

func _LoginService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoginService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoginService_LoginData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginDataReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServiceServer).LoginData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoginService_LoginData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServiceServer).LoginData(ctx, req.(*LoginDataReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoginService_LoginWithOtp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PhoneOtpRequst)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServiceServer).LoginWithOtp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoginService_LoginWithOtp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServiceServer).LoginWithOtp(ctx, req.(*PhoneOtpRequst))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoginService_LoginWithEmailOtp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailOtpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServiceServer).LoginWithEmailOtp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoginService_LoginWithEmailOtp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServiceServer).LoginWithEmailOtp(ctx, req.(*EmailOtpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoginService_GetUserUpdatedPermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserUpdatedPermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServiceServer).GetUserUpdatedPermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoginService_GetUserUpdatedPermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServiceServer).GetUserUpdatedPermission(ctx, req.(*GetUserUpdatedPermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LoginService_ServiceDesc is the grpc.ServiceDesc for LoginService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LoginService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "postgres_object_builder_service.LoginService",
	HandlerType: (*LoginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _LoginService_Login_Handler,
		},
		{
			MethodName: "LoginData",
			Handler:    _LoginService_LoginData_Handler,
		},
		{
			MethodName: "LoginWithOtp",
			Handler:    _LoginService_LoginWithOtp_Handler,
		},
		{
			MethodName: "LoginWithEmailOtp",
			Handler:    _LoginService_LoginWithEmailOtp_Handler,
		},
		{
			MethodName: "GetUserUpdatedPermission",
			Handler:    _LoginService_GetUserUpdatedPermission_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "postgres_login.proto",
}
