// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.29.2
// source: pg_ai_chat.proto

package new_object_builder_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AiChatServiceClient is the client API for AiChatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AiChatServiceClient interface {
	// Chats
	CreateChat(ctx context.Context, in *CreateChatRequest, opts ...grpc.CallOption) (*Chat, error)
	GetChat(ctx context.Context, in *ChatPrimaryKey, opts ...grpc.CallOption) (*Chat, error)
	GetChatByProjectId(ctx context.Context, in *ChatByProjectIdRequest, opts ...grpc.CallOption) (*Chat, error)
	GetAllChats(ctx context.Context, in *GetAllChatsRequest, opts ...grpc.CallOption) (*GetAllChatsResponse, error)
	UpdateChat(ctx context.Context, in *UpdateChatRequest, opts ...grpc.CallOption) (*Chat, error)
	DeleteChat(ctx context.Context, in *ChatPrimaryKey, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Messages
	CreateMessage(ctx context.Context, in *CreateMessageRequest, opts ...grpc.CallOption) (*Message, error)
	GetMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*GetMessagesResponse, error)
	DeleteMessage(ctx context.Context, in *MessagePrimaryKey, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// File Versions
	CreateFileVersion(ctx context.Context, in *CreateFileVersionRequest, opts ...grpc.CallOption) (*FileVersion, error)
	GetFileVersions(ctx context.Context, in *GetFileVersionsRequest, opts ...grpc.CallOption) (*GetFileVersionsResponse, error)
	GetFileVersionsByMessage(ctx context.Context, in *GetFileVersionsByMessageRequest, opts ...grpc.CallOption) (*GetFileVersionsResponse, error)
}

type aiChatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAiChatServiceClient(cc grpc.ClientConnInterface) AiChatServiceClient {
	return &aiChatServiceClient{cc}
}

func (c *aiChatServiceClient) CreateChat(ctx context.Context, in *CreateChatRequest, opts ...grpc.CallOption) (*Chat, error) {
	out := new(Chat)
	err := c.cc.Invoke(ctx, "/new_object_builder_service.AiChatService/CreateChat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiChatServiceClient) GetChat(ctx context.Context, in *ChatPrimaryKey, opts ...grpc.CallOption) (*Chat, error) {
	out := new(Chat)
	err := c.cc.Invoke(ctx, "/new_object_builder_service.AiChatService/GetChat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiChatServiceClient) GetChatByProjectId(ctx context.Context, in *ChatByProjectIdRequest, opts ...grpc.CallOption) (*Chat, error) {
	out := new(Chat)
	err := c.cc.Invoke(ctx, "/new_object_builder_service.AiChatService/GetChatByProjectId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiChatServiceClient) GetAllChats(ctx context.Context, in *GetAllChatsRequest, opts ...grpc.CallOption) (*GetAllChatsResponse, error) {
	out := new(GetAllChatsResponse)
	err := c.cc.Invoke(ctx, "/new_object_builder_service.AiChatService/GetAllChats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiChatServiceClient) UpdateChat(ctx context.Context, in *UpdateChatRequest, opts ...grpc.CallOption) (*Chat, error) {
	out := new(Chat)
	err := c.cc.Invoke(ctx, "/new_object_builder_service.AiChatService/UpdateChat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiChatServiceClient) DeleteChat(ctx context.Context, in *ChatPrimaryKey, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/new_object_builder_service.AiChatService/DeleteChat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiChatServiceClient) CreateMessage(ctx context.Context, in *CreateMessageRequest, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/new_object_builder_service.AiChatService/CreateMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiChatServiceClient) GetMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*GetMessagesResponse, error) {
	out := new(GetMessagesResponse)
	err := c.cc.Invoke(ctx, "/new_object_builder_service.AiChatService/GetMessages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiChatServiceClient) DeleteMessage(ctx context.Context, in *MessagePrimaryKey, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/new_object_builder_service.AiChatService/DeleteMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiChatServiceClient) CreateFileVersion(ctx context.Context, in *CreateFileVersionRequest, opts ...grpc.CallOption) (*FileVersion, error) {
	out := new(FileVersion)
	err := c.cc.Invoke(ctx, "/new_object_builder_service.AiChatService/CreateFileVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiChatServiceClient) GetFileVersions(ctx context.Context, in *GetFileVersionsRequest, opts ...grpc.CallOption) (*GetFileVersionsResponse, error) {
	out := new(GetFileVersionsResponse)
	err := c.cc.Invoke(ctx, "/new_object_builder_service.AiChatService/GetFileVersions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiChatServiceClient) GetFileVersionsByMessage(ctx context.Context, in *GetFileVersionsByMessageRequest, opts ...grpc.CallOption) (*GetFileVersionsResponse, error) {
	out := new(GetFileVersionsResponse)
	err := c.cc.Invoke(ctx, "/new_object_builder_service.AiChatService/GetFileVersionsByMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AiChatServiceServer is the server API for AiChatService service.
// All implementations must embed UnimplementedAiChatServiceServer
// for forward compatibility
type AiChatServiceServer interface {
	// Chats
	CreateChat(context.Context, *CreateChatRequest) (*Chat, error)
	GetChat(context.Context, *ChatPrimaryKey) (*Chat, error)
	GetChatByProjectId(context.Context, *ChatByProjectIdRequest) (*Chat, error)
	GetAllChats(context.Context, *GetAllChatsRequest) (*GetAllChatsResponse, error)
	UpdateChat(context.Context, *UpdateChatRequest) (*Chat, error)
	DeleteChat(context.Context, *ChatPrimaryKey) (*emptypb.Empty, error)
	// Messages
	CreateMessage(context.Context, *CreateMessageRequest) (*Message, error)
	GetMessages(context.Context, *GetMessagesRequest) (*GetMessagesResponse, error)
	DeleteMessage(context.Context, *MessagePrimaryKey) (*emptypb.Empty, error)
	// File Versions
	CreateFileVersion(context.Context, *CreateFileVersionRequest) (*FileVersion, error)
	GetFileVersions(context.Context, *GetFileVersionsRequest) (*GetFileVersionsResponse, error)
	GetFileVersionsByMessage(context.Context, *GetFileVersionsByMessageRequest) (*GetFileVersionsResponse, error)
	mustEmbedUnimplementedAiChatServiceServer()
}

// UnimplementedAiChatServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAiChatServiceServer struct {
}

func (UnimplementedAiChatServiceServer) CreateChat(context.Context, *CreateChatRequest) (*Chat, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateChat not implemented")
}
func (UnimplementedAiChatServiceServer) GetChat(context.Context, *ChatPrimaryKey) (*Chat, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChat not implemented")
}
func (UnimplementedAiChatServiceServer) GetChatByProjectId(context.Context, *ChatByProjectIdRequest) (*Chat, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChatByProjectId not implemented")
}
func (UnimplementedAiChatServiceServer) GetAllChats(context.Context, *GetAllChatsRequest) (*GetAllChatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllChats not implemented")
}
func (UnimplementedAiChatServiceServer) UpdateChat(context.Context, *UpdateChatRequest) (*Chat, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateChat not implemented")
}
func (UnimplementedAiChatServiceServer) DeleteChat(context.Context, *ChatPrimaryKey) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteChat not implemented")
}
func (UnimplementedAiChatServiceServer) CreateMessage(context.Context, *CreateMessageRequest) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMessage not implemented")
}
func (UnimplementedAiChatServiceServer) GetMessages(context.Context, *GetMessagesRequest) (*GetMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMessages not implemented")
}
func (UnimplementedAiChatServiceServer) DeleteMessage(context.Context, *MessagePrimaryKey) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMessage not implemented")
}
func (UnimplementedAiChatServiceServer) CreateFileVersion(context.Context, *CreateFileVersionRequest) (*FileVersion, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFileVersion not implemented")
}
func (UnimplementedAiChatServiceServer) GetFileVersions(context.Context, *GetFileVersionsRequest) (*GetFileVersionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFileVersions not implemented")
}
func (UnimplementedAiChatServiceServer) GetFileVersionsByMessage(context.Context, *GetFileVersionsByMessageRequest) (*GetFileVersionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFileVersionsByMessage not implemented")
}
func (UnimplementedAiChatServiceServer) mustEmbedUnimplementedAiChatServiceServer() {}

// UnsafeAiChatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AiChatServiceServer will
// result in compilation errors.
type UnsafeAiChatServiceServer interface {
	mustEmbedUnimplementedAiChatServiceServer()
}

func RegisterAiChatServiceServer(s grpc.ServiceRegistrar, srv AiChatServiceServer) {
	s.RegisterService(&AiChatService_ServiceDesc, srv)
}

func _AiChatService_CreateChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiChatServiceServer).CreateChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/new_object_builder_service.AiChatService/CreateChat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiChatServiceServer).CreateChat(ctx, req.(*CreateChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiChatService_GetChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatPrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiChatServiceServer).GetChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/new_object_builder_service.AiChatService/GetChat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiChatServiceServer).GetChat(ctx, req.(*ChatPrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiChatService_GetChatByProjectId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatByProjectIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiChatServiceServer).GetChatByProjectId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/new_object_builder_service.AiChatService/GetChatByProjectId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiChatServiceServer).GetChatByProjectId(ctx, req.(*ChatByProjectIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiChatService_GetAllChats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllChatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiChatServiceServer).GetAllChats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/new_object_builder_service.AiChatService/GetAllChats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiChatServiceServer).GetAllChats(ctx, req.(*GetAllChatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiChatService_UpdateChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiChatServiceServer).UpdateChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/new_object_builder_service.AiChatService/UpdateChat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiChatServiceServer).UpdateChat(ctx, req.(*UpdateChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiChatService_DeleteChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatPrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiChatServiceServer).DeleteChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/new_object_builder_service.AiChatService/DeleteChat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiChatServiceServer).DeleteChat(ctx, req.(*ChatPrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiChatService_CreateMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiChatServiceServer).CreateMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/new_object_builder_service.AiChatService/CreateMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiChatServiceServer).CreateMessage(ctx, req.(*CreateMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiChatService_GetMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiChatServiceServer).GetMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/new_object_builder_service.AiChatService/GetMessages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiChatServiceServer).GetMessages(ctx, req.(*GetMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiChatService_DeleteMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessagePrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiChatServiceServer).DeleteMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/new_object_builder_service.AiChatService/DeleteMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiChatServiceServer).DeleteMessage(ctx, req.(*MessagePrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiChatService_CreateFileVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFileVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiChatServiceServer).CreateFileVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/new_object_builder_service.AiChatService/CreateFileVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiChatServiceServer).CreateFileVersion(ctx, req.(*CreateFileVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiChatService_GetFileVersions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileVersionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiChatServiceServer).GetFileVersions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/new_object_builder_service.AiChatService/GetFileVersions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiChatServiceServer).GetFileVersions(ctx, req.(*GetFileVersionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiChatService_GetFileVersionsByMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileVersionsByMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiChatServiceServer).GetFileVersionsByMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/new_object_builder_service.AiChatService/GetFileVersionsByMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiChatServiceServer).GetFileVersionsByMessage(ctx, req.(*GetFileVersionsByMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AiChatService_ServiceDesc is the grpc.ServiceDesc for AiChatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AiChatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "new_object_builder_service.AiChatService",
	HandlerType: (*AiChatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateChat",
			Handler:    _AiChatService_CreateChat_Handler,
		},
		{
			MethodName: "GetChat",
			Handler:    _AiChatService_GetChat_Handler,
		},
		{
			MethodName: "GetChatByProjectId",
			Handler:    _AiChatService_GetChatByProjectId_Handler,
		},
		{
			MethodName: "GetAllChats",
			Handler:    _AiChatService_GetAllChats_Handler,
		},
		{
			MethodName: "UpdateChat",
			Handler:    _AiChatService_UpdateChat_Handler,
		},
		{
			MethodName: "DeleteChat",
			Handler:    _AiChatService_DeleteChat_Handler,
		},
		{
			MethodName: "CreateMessage",
			Handler:    _AiChatService_CreateMessage_Handler,
		},
		{
			MethodName: "GetMessages",
			Handler:    _AiChatService_GetMessages_Handler,
		},
		{
			MethodName: "DeleteMessage",
			Handler:    _AiChatService_DeleteMessage_Handler,
		},
		{
			MethodName: "CreateFileVersion",
			Handler:    _AiChatService_CreateFileVersion_Handler,
		},
		{
			MethodName: "GetFileVersions",
			Handler:    _AiChatService_GetFileVersions_Handler,
		},
		{
			MethodName: "GetFileVersionsByMessage",
			Handler:    _AiChatService_GetFileVersionsByMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pg_ai_chat.proto",
}
