// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.29.2
// source: pg_custom_endpoint.proto

package new_object_builder_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CustomEndpointServiceClient is the client API for CustomEndpointService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CustomEndpointServiceClient interface {
	Create(ctx context.Context, in *CreateCustomEndpointRequest, opts ...grpc.CallOption) (*CustomEndpoint, error)
	Update(ctx context.Context, in *CustomEndpoint, opts ...grpc.CallOption) (*CustomEndpoint, error)
	GetAll(ctx context.Context, in *GetCustomEndpointListRequest, opts ...grpc.CallOption) (*CustomEndpointList, error)
	GetById(ctx context.Context, in *CustomEndpointId, opts ...grpc.CallOption) (*CustomEndpoint, error)
	Delete(ctx context.Context, in *CustomEndpointId, opts ...grpc.CallOption) (*CustomEndpoint, error)
	Run(ctx context.Context, in *RunCustomEndpointRequest, opts ...grpc.CallOption) (*RunCustomEndpointResponse, error)
}

type customEndpointServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCustomEndpointServiceClient(cc grpc.ClientConnInterface) CustomEndpointServiceClient {
	return &customEndpointServiceClient{cc}
}

func (c *customEndpointServiceClient) Create(ctx context.Context, in *CreateCustomEndpointRequest, opts ...grpc.CallOption) (*CustomEndpoint, error) {
	out := new(CustomEndpoint)
	err := c.cc.Invoke(ctx, "/new_object_builder_service.CustomEndpointService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customEndpointServiceClient) Update(ctx context.Context, in *CustomEndpoint, opts ...grpc.CallOption) (*CustomEndpoint, error) {
	out := new(CustomEndpoint)
	err := c.cc.Invoke(ctx, "/new_object_builder_service.CustomEndpointService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customEndpointServiceClient) GetAll(ctx context.Context, in *GetCustomEndpointListRequest, opts ...grpc.CallOption) (*CustomEndpointList, error) {
	out := new(CustomEndpointList)
	err := c.cc.Invoke(ctx, "/new_object_builder_service.CustomEndpointService/GetAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customEndpointServiceClient) GetById(ctx context.Context, in *CustomEndpointId, opts ...grpc.CallOption) (*CustomEndpoint, error) {
	out := new(CustomEndpoint)
	err := c.cc.Invoke(ctx, "/new_object_builder_service.CustomEndpointService/GetById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customEndpointServiceClient) Delete(ctx context.Context, in *CustomEndpointId, opts ...grpc.CallOption) (*CustomEndpoint, error) {
	out := new(CustomEndpoint)
	err := c.cc.Invoke(ctx, "/new_object_builder_service.CustomEndpointService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customEndpointServiceClient) Run(ctx context.Context, in *RunCustomEndpointRequest, opts ...grpc.CallOption) (*RunCustomEndpointResponse, error) {
	out := new(RunCustomEndpointResponse)
	err := c.cc.Invoke(ctx, "/new_object_builder_service.CustomEndpointService/Run", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomEndpointServiceServer is the server API for CustomEndpointService service.
// All implementations must embed UnimplementedCustomEndpointServiceServer
// for forward compatibility
type CustomEndpointServiceServer interface {
	Create(context.Context, *CreateCustomEndpointRequest) (*CustomEndpoint, error)
	Update(context.Context, *CustomEndpoint) (*CustomEndpoint, error)
	GetAll(context.Context, *GetCustomEndpointListRequest) (*CustomEndpointList, error)
	GetById(context.Context, *CustomEndpointId) (*CustomEndpoint, error)
	Delete(context.Context, *CustomEndpointId) (*CustomEndpoint, error)
	Run(context.Context, *RunCustomEndpointRequest) (*RunCustomEndpointResponse, error)
	mustEmbedUnimplementedCustomEndpointServiceServer()
}

// UnimplementedCustomEndpointServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCustomEndpointServiceServer struct {
}

func (UnimplementedCustomEndpointServiceServer) Create(context.Context, *CreateCustomEndpointRequest) (*CustomEndpoint, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedCustomEndpointServiceServer) Update(context.Context, *CustomEndpoint) (*CustomEndpoint, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedCustomEndpointServiceServer) GetAll(context.Context, *GetCustomEndpointListRequest) (*CustomEndpointList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedCustomEndpointServiceServer) GetById(context.Context, *CustomEndpointId) (*CustomEndpoint, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetById not implemented")
}
func (UnimplementedCustomEndpointServiceServer) Delete(context.Context, *CustomEndpointId) (*CustomEndpoint, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedCustomEndpointServiceServer) Run(context.Context, *RunCustomEndpointRequest) (*RunCustomEndpointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedCustomEndpointServiceServer) mustEmbedUnimplementedCustomEndpointServiceServer() {}

// UnsafeCustomEndpointServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CustomEndpointServiceServer will
// result in compilation errors.
type UnsafeCustomEndpointServiceServer interface {
	mustEmbedUnimplementedCustomEndpointServiceServer()
}

func RegisterCustomEndpointServiceServer(s grpc.ServiceRegistrar, srv CustomEndpointServiceServer) {
	s.RegisterService(&CustomEndpointService_ServiceDesc, srv)
}

func _CustomEndpointService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCustomEndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomEndpointServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/new_object_builder_service.CustomEndpointService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomEndpointServiceServer).Create(ctx, req.(*CreateCustomEndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomEndpointService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomEndpoint)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomEndpointServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/new_object_builder_service.CustomEndpointService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomEndpointServiceServer).Update(ctx, req.(*CustomEndpoint))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomEndpointService_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCustomEndpointListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomEndpointServiceServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/new_object_builder_service.CustomEndpointService/GetAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomEndpointServiceServer).GetAll(ctx, req.(*GetCustomEndpointListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomEndpointService_GetById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomEndpointId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomEndpointServiceServer).GetById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/new_object_builder_service.CustomEndpointService/GetById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomEndpointServiceServer).GetById(ctx, req.(*CustomEndpointId))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomEndpointService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomEndpointId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomEndpointServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/new_object_builder_service.CustomEndpointService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomEndpointServiceServer).Delete(ctx, req.(*CustomEndpointId))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomEndpointService_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunCustomEndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomEndpointServiceServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/new_object_builder_service.CustomEndpointService/Run",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomEndpointServiceServer).Run(ctx, req.(*RunCustomEndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CustomEndpointService_ServiceDesc is the grpc.ServiceDesc for CustomEndpointService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CustomEndpointService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "new_object_builder_service.CustomEndpointService",
	HandlerType: (*CustomEndpointServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _CustomEndpointService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _CustomEndpointService_Update_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _CustomEndpointService_GetAll_Handler,
		},
		{
			MethodName: "GetById",
			Handler:    _CustomEndpointService_GetById_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _CustomEndpointService_Delete_Handler,
		},
		{
			MethodName: "Run",
			Handler:    _CustomEndpointService_Run_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pg_custom_endpoint.proto",
}
