// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: pg_docx_template.proto

package new_object_builder_service

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DocxTemplateServiceClient is the client API for DocxTemplateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DocxTemplateServiceClient interface {
	Create(ctx context.Context, in *CreateDocxTemplateRequest, opts ...grpc.CallOption) (*DocxTemplate, error)
	GetByID(ctx context.Context, in *DocxTemplatePrimaryKey, opts ...grpc.CallOption) (*DocxTemplate, error)
	GetAll(ctx context.Context, in *GetAllDocxTemplateRequest, opts ...grpc.CallOption) (*GetAllDocxTemplateResponse, error)
	Update(ctx context.Context, in *DocxTemplate, opts ...grpc.CallOption) (*DocxTemplate, error)
	Delete(ctx context.Context, in *DocxTemplatePrimaryKey, opts ...grpc.CallOption) (*empty.Empty, error)
}

type docxTemplateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDocxTemplateServiceClient(cc grpc.ClientConnInterface) DocxTemplateServiceClient {
	return &docxTemplateServiceClient{cc}
}

func (c *docxTemplateServiceClient) Create(ctx context.Context, in *CreateDocxTemplateRequest, opts ...grpc.CallOption) (*DocxTemplate, error) {
	out := new(DocxTemplate)
	err := c.cc.Invoke(ctx, "/new_object_builder_service.DocxTemplateService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *docxTemplateServiceClient) GetByID(ctx context.Context, in *DocxTemplatePrimaryKey, opts ...grpc.CallOption) (*DocxTemplate, error) {
	out := new(DocxTemplate)
	err := c.cc.Invoke(ctx, "/new_object_builder_service.DocxTemplateService/GetByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *docxTemplateServiceClient) GetAll(ctx context.Context, in *GetAllDocxTemplateRequest, opts ...grpc.CallOption) (*GetAllDocxTemplateResponse, error) {
	out := new(GetAllDocxTemplateResponse)
	err := c.cc.Invoke(ctx, "/new_object_builder_service.DocxTemplateService/GetAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *docxTemplateServiceClient) Update(ctx context.Context, in *DocxTemplate, opts ...grpc.CallOption) (*DocxTemplate, error) {
	out := new(DocxTemplate)
	err := c.cc.Invoke(ctx, "/new_object_builder_service.DocxTemplateService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *docxTemplateServiceClient) Delete(ctx context.Context, in *DocxTemplatePrimaryKey, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/new_object_builder_service.DocxTemplateService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DocxTemplateServiceServer is the server API for DocxTemplateService service.
// All implementations must embed UnimplementedDocxTemplateServiceServer
// for forward compatibility
type DocxTemplateServiceServer interface {
	Create(context.Context, *CreateDocxTemplateRequest) (*DocxTemplate, error)
	GetByID(context.Context, *DocxTemplatePrimaryKey) (*DocxTemplate, error)
	GetAll(context.Context, *GetAllDocxTemplateRequest) (*GetAllDocxTemplateResponse, error)
	Update(context.Context, *DocxTemplate) (*DocxTemplate, error)
	Delete(context.Context, *DocxTemplatePrimaryKey) (*empty.Empty, error)
	mustEmbedUnimplementedDocxTemplateServiceServer()
}

// UnimplementedDocxTemplateServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDocxTemplateServiceServer struct {
}

func (UnimplementedDocxTemplateServiceServer) Create(context.Context, *CreateDocxTemplateRequest) (*DocxTemplate, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedDocxTemplateServiceServer) GetByID(context.Context, *DocxTemplatePrimaryKey) (*DocxTemplate, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByID not implemented")
}
func (UnimplementedDocxTemplateServiceServer) GetAll(context.Context, *GetAllDocxTemplateRequest) (*GetAllDocxTemplateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedDocxTemplateServiceServer) Update(context.Context, *DocxTemplate) (*DocxTemplate, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedDocxTemplateServiceServer) Delete(context.Context, *DocxTemplatePrimaryKey) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedDocxTemplateServiceServer) mustEmbedUnimplementedDocxTemplateServiceServer() {}

// UnsafeDocxTemplateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DocxTemplateServiceServer will
// result in compilation errors.
type UnsafeDocxTemplateServiceServer interface {
	mustEmbedUnimplementedDocxTemplateServiceServer()
}

func RegisterDocxTemplateServiceServer(s grpc.ServiceRegistrar, srv DocxTemplateServiceServer) {
	s.RegisterService(&DocxTemplateService_ServiceDesc, srv)
}

func _DocxTemplateService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDocxTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocxTemplateServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/new_object_builder_service.DocxTemplateService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocxTemplateServiceServer).Create(ctx, req.(*CreateDocxTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocxTemplateService_GetByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DocxTemplatePrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocxTemplateServiceServer).GetByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/new_object_builder_service.DocxTemplateService/GetByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocxTemplateServiceServer).GetByID(ctx, req.(*DocxTemplatePrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocxTemplateService_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllDocxTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocxTemplateServiceServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/new_object_builder_service.DocxTemplateService/GetAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocxTemplateServiceServer).GetAll(ctx, req.(*GetAllDocxTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocxTemplateService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DocxTemplate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocxTemplateServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/new_object_builder_service.DocxTemplateService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocxTemplateServiceServer).Update(ctx, req.(*DocxTemplate))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocxTemplateService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DocxTemplatePrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocxTemplateServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/new_object_builder_service.DocxTemplateService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocxTemplateServiceServer).Delete(ctx, req.(*DocxTemplatePrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

// DocxTemplateService_ServiceDesc is the grpc.ServiceDesc for DocxTemplateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DocxTemplateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "new_object_builder_service.DocxTemplateService",
	HandlerType: (*DocxTemplateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _DocxTemplateService_Create_Handler,
		},
		{
			MethodName: "GetByID",
			Handler:    _DocxTemplateService_GetByID_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _DocxTemplateService_GetAll_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _DocxTemplateService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _DocxTemplateService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pg_docx_template.proto",
}
