// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.29.2
// source: pg_mcp_project.proto

package new_object_builder_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// McpProjectServiceClient is the client API for McpProjectService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type McpProjectServiceClient interface {
	CreateMcpProject(ctx context.Context, in *CreateMcpProjectReqeust, opts ...grpc.CallOption) (*McpProject, error)
	UpdateMcpProject(ctx context.Context, in *McpProject, opts ...grpc.CallOption) (*McpProject, error)
	GetAllMcpProject(ctx context.Context, in *GetMcpProjectListReq, opts ...grpc.CallOption) (*McpProjectList, error)
	GetMcpProjectFiles(ctx context.Context, in *McpProjectId, opts ...grpc.CallOption) (*McpProject, error)
	DeleteMcpProject(ctx context.Context, in *McpProjectId, opts ...grpc.CallOption) (*McpProject, error)
}

type mcpProjectServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMcpProjectServiceClient(cc grpc.ClientConnInterface) McpProjectServiceClient {
	return &mcpProjectServiceClient{cc}
}

func (c *mcpProjectServiceClient) CreateMcpProject(ctx context.Context, in *CreateMcpProjectReqeust, opts ...grpc.CallOption) (*McpProject, error) {
	out := new(McpProject)
	err := c.cc.Invoke(ctx, "/new_object_builder_service.McpProjectService/CreateMcpProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcpProjectServiceClient) UpdateMcpProject(ctx context.Context, in *McpProject, opts ...grpc.CallOption) (*McpProject, error) {
	out := new(McpProject)
	err := c.cc.Invoke(ctx, "/new_object_builder_service.McpProjectService/UpdateMcpProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcpProjectServiceClient) GetAllMcpProject(ctx context.Context, in *GetMcpProjectListReq, opts ...grpc.CallOption) (*McpProjectList, error) {
	out := new(McpProjectList)
	err := c.cc.Invoke(ctx, "/new_object_builder_service.McpProjectService/GetAllMcpProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcpProjectServiceClient) GetMcpProjectFiles(ctx context.Context, in *McpProjectId, opts ...grpc.CallOption) (*McpProject, error) {
	out := new(McpProject)
	err := c.cc.Invoke(ctx, "/new_object_builder_service.McpProjectService/GetMcpProjectFiles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcpProjectServiceClient) DeleteMcpProject(ctx context.Context, in *McpProjectId, opts ...grpc.CallOption) (*McpProject, error) {
	out := new(McpProject)
	err := c.cc.Invoke(ctx, "/new_object_builder_service.McpProjectService/DeleteMcpProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// McpProjectServiceServer is the server API for McpProjectService service.
// All implementations must embed UnimplementedMcpProjectServiceServer
// for forward compatibility
type McpProjectServiceServer interface {
	CreateMcpProject(context.Context, *CreateMcpProjectReqeust) (*McpProject, error)
	UpdateMcpProject(context.Context, *McpProject) (*McpProject, error)
	GetAllMcpProject(context.Context, *GetMcpProjectListReq) (*McpProjectList, error)
	GetMcpProjectFiles(context.Context, *McpProjectId) (*McpProject, error)
	DeleteMcpProject(context.Context, *McpProjectId) (*McpProject, error)
	mustEmbedUnimplementedMcpProjectServiceServer()
}

// UnimplementedMcpProjectServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMcpProjectServiceServer struct {
}

func (UnimplementedMcpProjectServiceServer) CreateMcpProject(context.Context, *CreateMcpProjectReqeust) (*McpProject, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMcpProject not implemented")
}
func (UnimplementedMcpProjectServiceServer) UpdateMcpProject(context.Context, *McpProject) (*McpProject, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMcpProject not implemented")
}
func (UnimplementedMcpProjectServiceServer) GetAllMcpProject(context.Context, *GetMcpProjectListReq) (*McpProjectList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllMcpProject not implemented")
}
func (UnimplementedMcpProjectServiceServer) GetMcpProjectFiles(context.Context, *McpProjectId) (*McpProject, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMcpProjectFiles not implemented")
}
func (UnimplementedMcpProjectServiceServer) DeleteMcpProject(context.Context, *McpProjectId) (*McpProject, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMcpProject not implemented")
}
func (UnimplementedMcpProjectServiceServer) mustEmbedUnimplementedMcpProjectServiceServer() {}

// UnsafeMcpProjectServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to McpProjectServiceServer will
// result in compilation errors.
type UnsafeMcpProjectServiceServer interface {
	mustEmbedUnimplementedMcpProjectServiceServer()
}

func RegisterMcpProjectServiceServer(s grpc.ServiceRegistrar, srv McpProjectServiceServer) {
	s.RegisterService(&McpProjectService_ServiceDesc, srv)
}

func _McpProjectService_CreateMcpProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMcpProjectReqeust)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McpProjectServiceServer).CreateMcpProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/new_object_builder_service.McpProjectService/CreateMcpProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McpProjectServiceServer).CreateMcpProject(ctx, req.(*CreateMcpProjectReqeust))
	}
	return interceptor(ctx, in, info, handler)
}

func _McpProjectService_UpdateMcpProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(McpProject)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McpProjectServiceServer).UpdateMcpProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/new_object_builder_service.McpProjectService/UpdateMcpProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McpProjectServiceServer).UpdateMcpProject(ctx, req.(*McpProject))
	}
	return interceptor(ctx, in, info, handler)
}

func _McpProjectService_GetAllMcpProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMcpProjectListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McpProjectServiceServer).GetAllMcpProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/new_object_builder_service.McpProjectService/GetAllMcpProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McpProjectServiceServer).GetAllMcpProject(ctx, req.(*GetMcpProjectListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _McpProjectService_GetMcpProjectFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(McpProjectId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McpProjectServiceServer).GetMcpProjectFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/new_object_builder_service.McpProjectService/GetMcpProjectFiles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McpProjectServiceServer).GetMcpProjectFiles(ctx, req.(*McpProjectId))
	}
	return interceptor(ctx, in, info, handler)
}

func _McpProjectService_DeleteMcpProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(McpProjectId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McpProjectServiceServer).DeleteMcpProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/new_object_builder_service.McpProjectService/DeleteMcpProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McpProjectServiceServer).DeleteMcpProject(ctx, req.(*McpProjectId))
	}
	return interceptor(ctx, in, info, handler)
}

// McpProjectService_ServiceDesc is the grpc.ServiceDesc for McpProjectService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var McpProjectService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "new_object_builder_service.McpProjectService",
	HandlerType: (*McpProjectServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMcpProject",
			Handler:    _McpProjectService_CreateMcpProject_Handler,
		},
		{
			MethodName: "UpdateMcpProject",
			Handler:    _McpProjectService_UpdateMcpProject_Handler,
		},
		{
			MethodName: "GetAllMcpProject",
			Handler:    _McpProjectService_GetAllMcpProject_Handler,
		},
		{
			MethodName: "GetMcpProjectFiles",
			Handler:    _McpProjectService_GetMcpProjectFiles_Handler,
		},
		{
			MethodName: "DeleteMcpProject",
			Handler:    _McpProjectService_DeleteMcpProject_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pg_mcp_project.proto",
}
