// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.29.2
// source: pg_project_folders.proto

package new_object_builder_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ProjectFoldersServiceClient is the client API for ProjectFoldersService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProjectFoldersServiceClient interface {
	CreateProjectFolder(ctx context.Context, in *CreateProjectFolderRequest, opts ...grpc.CallOption) (*ProjectFolder, error)
	GetProjectFolderById(ctx context.Context, in *ProjectFolderPrimaryKey, opts ...grpc.CallOption) (*ProjectFolder, error)
	GetAllProjectFolders(ctx context.Context, in *GetAllProjectFoldersRequest, opts ...grpc.CallOption) (*GetAllProjectFoldersResponse, error)
	UpdateProjectFolder(ctx context.Context, in *UpdateProjectFolderRequest, opts ...grpc.CallOption) (*ProjectFolder, error)
	DeleteProjectFolder(ctx context.Context, in *ProjectFolderPrimaryKey, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateProjectFolderOrder(ctx context.Context, in *UpdateProjectFolderOrderRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type projectFoldersServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProjectFoldersServiceClient(cc grpc.ClientConnInterface) ProjectFoldersServiceClient {
	return &projectFoldersServiceClient{cc}
}

func (c *projectFoldersServiceClient) CreateProjectFolder(ctx context.Context, in *CreateProjectFolderRequest, opts ...grpc.CallOption) (*ProjectFolder, error) {
	out := new(ProjectFolder)
	err := c.cc.Invoke(ctx, "/new_object_builder_service.ProjectFoldersService/CreateProjectFolder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectFoldersServiceClient) GetProjectFolderById(ctx context.Context, in *ProjectFolderPrimaryKey, opts ...grpc.CallOption) (*ProjectFolder, error) {
	out := new(ProjectFolder)
	err := c.cc.Invoke(ctx, "/new_object_builder_service.ProjectFoldersService/GetProjectFolderById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectFoldersServiceClient) GetAllProjectFolders(ctx context.Context, in *GetAllProjectFoldersRequest, opts ...grpc.CallOption) (*GetAllProjectFoldersResponse, error) {
	out := new(GetAllProjectFoldersResponse)
	err := c.cc.Invoke(ctx, "/new_object_builder_service.ProjectFoldersService/GetAllProjectFolders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectFoldersServiceClient) UpdateProjectFolder(ctx context.Context, in *UpdateProjectFolderRequest, opts ...grpc.CallOption) (*ProjectFolder, error) {
	out := new(ProjectFolder)
	err := c.cc.Invoke(ctx, "/new_object_builder_service.ProjectFoldersService/UpdateProjectFolder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectFoldersServiceClient) DeleteProjectFolder(ctx context.Context, in *ProjectFolderPrimaryKey, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/new_object_builder_service.ProjectFoldersService/DeleteProjectFolder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectFoldersServiceClient) UpdateProjectFolderOrder(ctx context.Context, in *UpdateProjectFolderOrderRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/new_object_builder_service.ProjectFoldersService/UpdateProjectFolderOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProjectFoldersServiceServer is the server API for ProjectFoldersService service.
// All implementations must embed UnimplementedProjectFoldersServiceServer
// for forward compatibility
type ProjectFoldersServiceServer interface {
	CreateProjectFolder(context.Context, *CreateProjectFolderRequest) (*ProjectFolder, error)
	GetProjectFolderById(context.Context, *ProjectFolderPrimaryKey) (*ProjectFolder, error)
	GetAllProjectFolders(context.Context, *GetAllProjectFoldersRequest) (*GetAllProjectFoldersResponse, error)
	UpdateProjectFolder(context.Context, *UpdateProjectFolderRequest) (*ProjectFolder, error)
	DeleteProjectFolder(context.Context, *ProjectFolderPrimaryKey) (*emptypb.Empty, error)
	UpdateProjectFolderOrder(context.Context, *UpdateProjectFolderOrderRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedProjectFoldersServiceServer()
}

// UnimplementedProjectFoldersServiceServer must be embedded to have forward compatible implementations.
type UnimplementedProjectFoldersServiceServer struct {
}

func (UnimplementedProjectFoldersServiceServer) CreateProjectFolder(context.Context, *CreateProjectFolderRequest) (*ProjectFolder, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProjectFolder not implemented")
}
func (UnimplementedProjectFoldersServiceServer) GetProjectFolderById(context.Context, *ProjectFolderPrimaryKey) (*ProjectFolder, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProjectFolderById not implemented")
}
func (UnimplementedProjectFoldersServiceServer) GetAllProjectFolders(context.Context, *GetAllProjectFoldersRequest) (*GetAllProjectFoldersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllProjectFolders not implemented")
}
func (UnimplementedProjectFoldersServiceServer) UpdateProjectFolder(context.Context, *UpdateProjectFolderRequest) (*ProjectFolder, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProjectFolder not implemented")
}
func (UnimplementedProjectFoldersServiceServer) DeleteProjectFolder(context.Context, *ProjectFolderPrimaryKey) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProjectFolder not implemented")
}
func (UnimplementedProjectFoldersServiceServer) UpdateProjectFolderOrder(context.Context, *UpdateProjectFolderOrderRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProjectFolderOrder not implemented")
}
func (UnimplementedProjectFoldersServiceServer) mustEmbedUnimplementedProjectFoldersServiceServer() {}

// UnsafeProjectFoldersServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProjectFoldersServiceServer will
// result in compilation errors.
type UnsafeProjectFoldersServiceServer interface {
	mustEmbedUnimplementedProjectFoldersServiceServer()
}

func RegisterProjectFoldersServiceServer(s grpc.ServiceRegistrar, srv ProjectFoldersServiceServer) {
	s.RegisterService(&ProjectFoldersService_ServiceDesc, srv)
}

func _ProjectFoldersService_CreateProjectFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProjectFolderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectFoldersServiceServer).CreateProjectFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/new_object_builder_service.ProjectFoldersService/CreateProjectFolder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectFoldersServiceServer).CreateProjectFolder(ctx, req.(*CreateProjectFolderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectFoldersService_GetProjectFolderById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectFolderPrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectFoldersServiceServer).GetProjectFolderById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/new_object_builder_service.ProjectFoldersService/GetProjectFolderById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectFoldersServiceServer).GetProjectFolderById(ctx, req.(*ProjectFolderPrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectFoldersService_GetAllProjectFolders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllProjectFoldersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectFoldersServiceServer).GetAllProjectFolders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/new_object_builder_service.ProjectFoldersService/GetAllProjectFolders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectFoldersServiceServer).GetAllProjectFolders(ctx, req.(*GetAllProjectFoldersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectFoldersService_UpdateProjectFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProjectFolderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectFoldersServiceServer).UpdateProjectFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/new_object_builder_service.ProjectFoldersService/UpdateProjectFolder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectFoldersServiceServer).UpdateProjectFolder(ctx, req.(*UpdateProjectFolderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectFoldersService_DeleteProjectFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectFolderPrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectFoldersServiceServer).DeleteProjectFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/new_object_builder_service.ProjectFoldersService/DeleteProjectFolder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectFoldersServiceServer).DeleteProjectFolder(ctx, req.(*ProjectFolderPrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectFoldersService_UpdateProjectFolderOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProjectFolderOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectFoldersServiceServer).UpdateProjectFolderOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/new_object_builder_service.ProjectFoldersService/UpdateProjectFolderOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectFoldersServiceServer).UpdateProjectFolderOrder(ctx, req.(*UpdateProjectFolderOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProjectFoldersService_ServiceDesc is the grpc.ServiceDesc for ProjectFoldersService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProjectFoldersService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "new_object_builder_service.ProjectFoldersService",
	HandlerType: (*ProjectFoldersServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProjectFolder",
			Handler:    _ProjectFoldersService_CreateProjectFolder_Handler,
		},
		{
			MethodName: "GetProjectFolderById",
			Handler:    _ProjectFoldersService_GetProjectFolderById_Handler,
		},
		{
			MethodName: "GetAllProjectFolders",
			Handler:    _ProjectFoldersService_GetAllProjectFolders_Handler,
		},
		{
			MethodName: "UpdateProjectFolder",
			Handler:    _ProjectFoldersService_UpdateProjectFolder_Handler,
		},
		{
			MethodName: "DeleteProjectFolder",
			Handler:    _ProjectFoldersService_DeleteProjectFolder_Handler,
		},
		{
			MethodName: "UpdateProjectFolderOrder",
			Handler:    _ProjectFoldersService_UpdateProjectFolderOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pg_project_folders.proto",
}
