// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.29.2
// source: pg_table.proto

package new_object_builder_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TableServiceClient is the client API for TableService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TableServiceClient interface {
	Create(ctx context.Context, in *CreateTableRequest, opts ...grpc.CallOption) (*CreateTableResponse, error)
	GetByID(ctx context.Context, in *TablePrimaryKey, opts ...grpc.CallOption) (*Table, error)
	GetAll(ctx context.Context, in *GetAllTablesRequest, opts ...grpc.CallOption) (*GetAllTablesResponse, error)
	Update(ctx context.Context, in *UpdateTableRequest, opts ...grpc.CallOption) (*Table, error)
	Delete(ctx context.Context, in *TablePrimaryKey, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetListTableHistory(ctx context.Context, in *GetTableHistoryRequest, opts ...grpc.CallOption) (*GetTableHistoryResponse, error)
	GetTableHistoryById(ctx context.Context, in *TableHistoryPrimaryKey, opts ...grpc.CallOption) (*Table, error)
	RevertTableHistory(ctx context.Context, in *RevertTableHistoryRequest, opts ...grpc.CallOption) (*TableHistory, error)
	InsertVersionsToCommit(ctx context.Context, in *InsertVersionsToCommitRequest, opts ...grpc.CallOption) (*TableHistory, error)
	GetTablesByLabel(ctx context.Context, in *GetTablesByLabelReq, opts ...grpc.CallOption) (*GetAllTablesResponse, error)
	GetChart(ctx context.Context, in *ChartPrimaryKey, opts ...grpc.CallOption) (*GetChartResponse, error)
	CreateConnectionAndSchema(ctx context.Context, in *CreateConnectionAndSchemaReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetTrackedUntrackedTables(ctx context.Context, in *GetTrackedUntrackedTablesReq, opts ...grpc.CallOption) (*GetTrackedUntrackedTableResp, error)
	GetTrackedConnections(ctx context.Context, in *GetTrackedConnectionsReq, opts ...grpc.CallOption) (*GetTrackedConnectionsResp, error)
	TrackTables(ctx context.Context, in *TrackedTablesByIdsReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UntrackTableById(ctx context.Context, in *UntrackTableByIdReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type tableServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTableServiceClient(cc grpc.ClientConnInterface) TableServiceClient {
	return &tableServiceClient{cc}
}

func (c *tableServiceClient) Create(ctx context.Context, in *CreateTableRequest, opts ...grpc.CallOption) (*CreateTableResponse, error) {
	out := new(CreateTableResponse)
	err := c.cc.Invoke(ctx, "/new_object_builder_service.TableService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tableServiceClient) GetByID(ctx context.Context, in *TablePrimaryKey, opts ...grpc.CallOption) (*Table, error) {
	out := new(Table)
	err := c.cc.Invoke(ctx, "/new_object_builder_service.TableService/GetByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tableServiceClient) GetAll(ctx context.Context, in *GetAllTablesRequest, opts ...grpc.CallOption) (*GetAllTablesResponse, error) {
	out := new(GetAllTablesResponse)
	err := c.cc.Invoke(ctx, "/new_object_builder_service.TableService/GetAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tableServiceClient) Update(ctx context.Context, in *UpdateTableRequest, opts ...grpc.CallOption) (*Table, error) {
	out := new(Table)
	err := c.cc.Invoke(ctx, "/new_object_builder_service.TableService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tableServiceClient) Delete(ctx context.Context, in *TablePrimaryKey, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/new_object_builder_service.TableService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tableServiceClient) GetListTableHistory(ctx context.Context, in *GetTableHistoryRequest, opts ...grpc.CallOption) (*GetTableHistoryResponse, error) {
	out := new(GetTableHistoryResponse)
	err := c.cc.Invoke(ctx, "/new_object_builder_service.TableService/GetListTableHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tableServiceClient) GetTableHistoryById(ctx context.Context, in *TableHistoryPrimaryKey, opts ...grpc.CallOption) (*Table, error) {
	out := new(Table)
	err := c.cc.Invoke(ctx, "/new_object_builder_service.TableService/GetTableHistoryById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tableServiceClient) RevertTableHistory(ctx context.Context, in *RevertTableHistoryRequest, opts ...grpc.CallOption) (*TableHistory, error) {
	out := new(TableHistory)
	err := c.cc.Invoke(ctx, "/new_object_builder_service.TableService/RevertTableHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tableServiceClient) InsertVersionsToCommit(ctx context.Context, in *InsertVersionsToCommitRequest, opts ...grpc.CallOption) (*TableHistory, error) {
	out := new(TableHistory)
	err := c.cc.Invoke(ctx, "/new_object_builder_service.TableService/InsertVersionsToCommit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tableServiceClient) GetTablesByLabel(ctx context.Context, in *GetTablesByLabelReq, opts ...grpc.CallOption) (*GetAllTablesResponse, error) {
	out := new(GetAllTablesResponse)
	err := c.cc.Invoke(ctx, "/new_object_builder_service.TableService/GetTablesByLabel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tableServiceClient) GetChart(ctx context.Context, in *ChartPrimaryKey, opts ...grpc.CallOption) (*GetChartResponse, error) {
	out := new(GetChartResponse)
	err := c.cc.Invoke(ctx, "/new_object_builder_service.TableService/GetChart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tableServiceClient) CreateConnectionAndSchema(ctx context.Context, in *CreateConnectionAndSchemaReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/new_object_builder_service.TableService/CreateConnectionAndSchema", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tableServiceClient) GetTrackedUntrackedTables(ctx context.Context, in *GetTrackedUntrackedTablesReq, opts ...grpc.CallOption) (*GetTrackedUntrackedTableResp, error) {
	out := new(GetTrackedUntrackedTableResp)
	err := c.cc.Invoke(ctx, "/new_object_builder_service.TableService/GetTrackedUntrackedTables", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tableServiceClient) GetTrackedConnections(ctx context.Context, in *GetTrackedConnectionsReq, opts ...grpc.CallOption) (*GetTrackedConnectionsResp, error) {
	out := new(GetTrackedConnectionsResp)
	err := c.cc.Invoke(ctx, "/new_object_builder_service.TableService/GetTrackedConnections", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tableServiceClient) TrackTables(ctx context.Context, in *TrackedTablesByIdsReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/new_object_builder_service.TableService/TrackTables", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tableServiceClient) UntrackTableById(ctx context.Context, in *UntrackTableByIdReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/new_object_builder_service.TableService/UntrackTableById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TableServiceServer is the server API for TableService service.
// All implementations must embed UnimplementedTableServiceServer
// for forward compatibility
type TableServiceServer interface {
	Create(context.Context, *CreateTableRequest) (*CreateTableResponse, error)
	GetByID(context.Context, *TablePrimaryKey) (*Table, error)
	GetAll(context.Context, *GetAllTablesRequest) (*GetAllTablesResponse, error)
	Update(context.Context, *UpdateTableRequest) (*Table, error)
	Delete(context.Context, *TablePrimaryKey) (*emptypb.Empty, error)
	GetListTableHistory(context.Context, *GetTableHistoryRequest) (*GetTableHistoryResponse, error)
	GetTableHistoryById(context.Context, *TableHistoryPrimaryKey) (*Table, error)
	RevertTableHistory(context.Context, *RevertTableHistoryRequest) (*TableHistory, error)
	InsertVersionsToCommit(context.Context, *InsertVersionsToCommitRequest) (*TableHistory, error)
	GetTablesByLabel(context.Context, *GetTablesByLabelReq) (*GetAllTablesResponse, error)
	GetChart(context.Context, *ChartPrimaryKey) (*GetChartResponse, error)
	CreateConnectionAndSchema(context.Context, *CreateConnectionAndSchemaReq) (*emptypb.Empty, error)
	GetTrackedUntrackedTables(context.Context, *GetTrackedUntrackedTablesReq) (*GetTrackedUntrackedTableResp, error)
	GetTrackedConnections(context.Context, *GetTrackedConnectionsReq) (*GetTrackedConnectionsResp, error)
	TrackTables(context.Context, *TrackedTablesByIdsReq) (*emptypb.Empty, error)
	UntrackTableById(context.Context, *UntrackTableByIdReq) (*emptypb.Empty, error)
	mustEmbedUnimplementedTableServiceServer()
}

// UnimplementedTableServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTableServiceServer struct {
}

func (UnimplementedTableServiceServer) Create(context.Context, *CreateTableRequest) (*CreateTableResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedTableServiceServer) GetByID(context.Context, *TablePrimaryKey) (*Table, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByID not implemented")
}
func (UnimplementedTableServiceServer) GetAll(context.Context, *GetAllTablesRequest) (*GetAllTablesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedTableServiceServer) Update(context.Context, *UpdateTableRequest) (*Table, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedTableServiceServer) Delete(context.Context, *TablePrimaryKey) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedTableServiceServer) GetListTableHistory(context.Context, *GetTableHistoryRequest) (*GetTableHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetListTableHistory not implemented")
}
func (UnimplementedTableServiceServer) GetTableHistoryById(context.Context, *TableHistoryPrimaryKey) (*Table, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTableHistoryById not implemented")
}
func (UnimplementedTableServiceServer) RevertTableHistory(context.Context, *RevertTableHistoryRequest) (*TableHistory, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevertTableHistory not implemented")
}
func (UnimplementedTableServiceServer) InsertVersionsToCommit(context.Context, *InsertVersionsToCommitRequest) (*TableHistory, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertVersionsToCommit not implemented")
}
func (UnimplementedTableServiceServer) GetTablesByLabel(context.Context, *GetTablesByLabelReq) (*GetAllTablesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTablesByLabel not implemented")
}
func (UnimplementedTableServiceServer) GetChart(context.Context, *ChartPrimaryKey) (*GetChartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChart not implemented")
}
func (UnimplementedTableServiceServer) CreateConnectionAndSchema(context.Context, *CreateConnectionAndSchemaReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateConnectionAndSchema not implemented")
}
func (UnimplementedTableServiceServer) GetTrackedUntrackedTables(context.Context, *GetTrackedUntrackedTablesReq) (*GetTrackedUntrackedTableResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTrackedUntrackedTables not implemented")
}
func (UnimplementedTableServiceServer) GetTrackedConnections(context.Context, *GetTrackedConnectionsReq) (*GetTrackedConnectionsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTrackedConnections not implemented")
}
func (UnimplementedTableServiceServer) TrackTables(context.Context, *TrackedTablesByIdsReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TrackTables not implemented")
}
func (UnimplementedTableServiceServer) UntrackTableById(context.Context, *UntrackTableByIdReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UntrackTableById not implemented")
}
func (UnimplementedTableServiceServer) mustEmbedUnimplementedTableServiceServer() {}

// UnsafeTableServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TableServiceServer will
// result in compilation errors.
type UnsafeTableServiceServer interface {
	mustEmbedUnimplementedTableServiceServer()
}

func RegisterTableServiceServer(s grpc.ServiceRegistrar, srv TableServiceServer) {
	s.RegisterService(&TableService_ServiceDesc, srv)
}

func _TableService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/new_object_builder_service.TableService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableServiceServer).Create(ctx, req.(*CreateTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TableService_GetByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TablePrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableServiceServer).GetByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/new_object_builder_service.TableService/GetByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableServiceServer).GetByID(ctx, req.(*TablePrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _TableService_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllTablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableServiceServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/new_object_builder_service.TableService/GetAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableServiceServer).GetAll(ctx, req.(*GetAllTablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TableService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/new_object_builder_service.TableService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableServiceServer).Update(ctx, req.(*UpdateTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TableService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TablePrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/new_object_builder_service.TableService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableServiceServer).Delete(ctx, req.(*TablePrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _TableService_GetListTableHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTableHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableServiceServer).GetListTableHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/new_object_builder_service.TableService/GetListTableHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableServiceServer).GetListTableHistory(ctx, req.(*GetTableHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TableService_GetTableHistoryById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TableHistoryPrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableServiceServer).GetTableHistoryById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/new_object_builder_service.TableService/GetTableHistoryById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableServiceServer).GetTableHistoryById(ctx, req.(*TableHistoryPrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _TableService_RevertTableHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevertTableHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableServiceServer).RevertTableHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/new_object_builder_service.TableService/RevertTableHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableServiceServer).RevertTableHistory(ctx, req.(*RevertTableHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TableService_InsertVersionsToCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertVersionsToCommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableServiceServer).InsertVersionsToCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/new_object_builder_service.TableService/InsertVersionsToCommit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableServiceServer).InsertVersionsToCommit(ctx, req.(*InsertVersionsToCommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TableService_GetTablesByLabel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTablesByLabelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableServiceServer).GetTablesByLabel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/new_object_builder_service.TableService/GetTablesByLabel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableServiceServer).GetTablesByLabel(ctx, req.(*GetTablesByLabelReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TableService_GetChart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChartPrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableServiceServer).GetChart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/new_object_builder_service.TableService/GetChart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableServiceServer).GetChart(ctx, req.(*ChartPrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _TableService_CreateConnectionAndSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateConnectionAndSchemaReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableServiceServer).CreateConnectionAndSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/new_object_builder_service.TableService/CreateConnectionAndSchema",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableServiceServer).CreateConnectionAndSchema(ctx, req.(*CreateConnectionAndSchemaReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TableService_GetTrackedUntrackedTables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrackedUntrackedTablesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableServiceServer).GetTrackedUntrackedTables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/new_object_builder_service.TableService/GetTrackedUntrackedTables",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableServiceServer).GetTrackedUntrackedTables(ctx, req.(*GetTrackedUntrackedTablesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TableService_GetTrackedConnections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrackedConnectionsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableServiceServer).GetTrackedConnections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/new_object_builder_service.TableService/GetTrackedConnections",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableServiceServer).GetTrackedConnections(ctx, req.(*GetTrackedConnectionsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TableService_TrackTables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrackedTablesByIdsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableServiceServer).TrackTables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/new_object_builder_service.TableService/TrackTables",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableServiceServer).TrackTables(ctx, req.(*TrackedTablesByIdsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TableService_UntrackTableById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UntrackTableByIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableServiceServer).UntrackTableById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/new_object_builder_service.TableService/UntrackTableById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableServiceServer).UntrackTableById(ctx, req.(*UntrackTableByIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

// TableService_ServiceDesc is the grpc.ServiceDesc for TableService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TableService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "new_object_builder_service.TableService",
	HandlerType: (*TableServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _TableService_Create_Handler,
		},
		{
			MethodName: "GetByID",
			Handler:    _TableService_GetByID_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _TableService_GetAll_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _TableService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _TableService_Delete_Handler,
		},
		{
			MethodName: "GetListTableHistory",
			Handler:    _TableService_GetListTableHistory_Handler,
		},
		{
			MethodName: "GetTableHistoryById",
			Handler:    _TableService_GetTableHistoryById_Handler,
		},
		{
			MethodName: "RevertTableHistory",
			Handler:    _TableService_RevertTableHistory_Handler,
		},
		{
			MethodName: "InsertVersionsToCommit",
			Handler:    _TableService_InsertVersionsToCommit_Handler,
		},
		{
			MethodName: "GetTablesByLabel",
			Handler:    _TableService_GetTablesByLabel_Handler,
		},
		{
			MethodName: "GetChart",
			Handler:    _TableService_GetChart_Handler,
		},
		{
			MethodName: "CreateConnectionAndSchema",
			Handler:    _TableService_CreateConnectionAndSchema_Handler,
		},
		{
			MethodName: "GetTrackedUntrackedTables",
			Handler:    _TableService_GetTrackedUntrackedTables_Handler,
		},
		{
			MethodName: "GetTrackedConnections",
			Handler:    _TableService_GetTrackedConnections_Handler,
		},
		{
			MethodName: "TrackTables",
			Handler:    _TableService_TrackTables_Handler,
		},
		{
			MethodName: "UntrackTableById",
			Handler:    _TableService_UntrackTableById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pg_table.proto",
}
