// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: login.proto

package object_builder_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LoginServiceClient is the client API for LoginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LoginServiceClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*V2LoginResponse, error)
	LoginData(ctx context.Context, in *LoginDataReq, opts ...grpc.CallOption) (*LoginDataRes, error)
	LoginWithOtp(ctx context.Context, in *PhoneOtpRequst, opts ...grpc.CallOption) (*V2LoginResponse, error)
	LoginWithEmailOtp(ctx context.Context, in *EmailOtpRequest, opts ...grpc.CallOption) (*V2LoginResponse, error)
	GetUserUpdatedPermission(ctx context.Context, in *GetUserUpdatedPermissionRequest, opts ...grpc.CallOption) (*V2LoginResponse, error)
	LoginDataByUserId(ctx context.Context, in *LoginDataReq, opts ...grpc.CallOption) (*LoginDataRes, error)
	GetConnetionOptions(ctx context.Context, in *GetConnetionOptionsRequest, opts ...grpc.CallOption) (*GetConnectionOptionsResponse, error)
	UpdateUserPassword(ctx context.Context, in *UpdateUserPasswordRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type loginServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLoginServiceClient(cc grpc.ClientConnInterface) LoginServiceClient {
	return &loginServiceClient{cc}
}

func (c *loginServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*V2LoginResponse, error) {
	out := new(V2LoginResponse)
	err := c.cc.Invoke(ctx, "/object_builder_service.LoginService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginServiceClient) LoginData(ctx context.Context, in *LoginDataReq, opts ...grpc.CallOption) (*LoginDataRes, error) {
	out := new(LoginDataRes)
	err := c.cc.Invoke(ctx, "/object_builder_service.LoginService/LoginData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginServiceClient) LoginWithOtp(ctx context.Context, in *PhoneOtpRequst, opts ...grpc.CallOption) (*V2LoginResponse, error) {
	out := new(V2LoginResponse)
	err := c.cc.Invoke(ctx, "/object_builder_service.LoginService/LoginWithOtp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginServiceClient) LoginWithEmailOtp(ctx context.Context, in *EmailOtpRequest, opts ...grpc.CallOption) (*V2LoginResponse, error) {
	out := new(V2LoginResponse)
	err := c.cc.Invoke(ctx, "/object_builder_service.LoginService/LoginWithEmailOtp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginServiceClient) GetUserUpdatedPermission(ctx context.Context, in *GetUserUpdatedPermissionRequest, opts ...grpc.CallOption) (*V2LoginResponse, error) {
	out := new(V2LoginResponse)
	err := c.cc.Invoke(ctx, "/object_builder_service.LoginService/GetUserUpdatedPermission", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginServiceClient) LoginDataByUserId(ctx context.Context, in *LoginDataReq, opts ...grpc.CallOption) (*LoginDataRes, error) {
	out := new(LoginDataRes)
	err := c.cc.Invoke(ctx, "/object_builder_service.LoginService/LoginDataByUserId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginServiceClient) GetConnetionOptions(ctx context.Context, in *GetConnetionOptionsRequest, opts ...grpc.CallOption) (*GetConnectionOptionsResponse, error) {
	out := new(GetConnectionOptionsResponse)
	err := c.cc.Invoke(ctx, "/object_builder_service.LoginService/GetConnetionOptions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginServiceClient) UpdateUserPassword(ctx context.Context, in *UpdateUserPasswordRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/object_builder_service.LoginService/UpdateUserPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoginServiceServer is the server API for LoginService service.
// All implementations must embed UnimplementedLoginServiceServer
// for forward compatibility
type LoginServiceServer interface {
	Login(context.Context, *LoginRequest) (*V2LoginResponse, error)
	LoginData(context.Context, *LoginDataReq) (*LoginDataRes, error)
	LoginWithOtp(context.Context, *PhoneOtpRequst) (*V2LoginResponse, error)
	LoginWithEmailOtp(context.Context, *EmailOtpRequest) (*V2LoginResponse, error)
	GetUserUpdatedPermission(context.Context, *GetUserUpdatedPermissionRequest) (*V2LoginResponse, error)
	LoginDataByUserId(context.Context, *LoginDataReq) (*LoginDataRes, error)
	GetConnetionOptions(context.Context, *GetConnetionOptionsRequest) (*GetConnectionOptionsResponse, error)
	UpdateUserPassword(context.Context, *UpdateUserPasswordRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedLoginServiceServer()
}

// UnimplementedLoginServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLoginServiceServer struct {
}

func (UnimplementedLoginServiceServer) Login(context.Context, *LoginRequest) (*V2LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedLoginServiceServer) LoginData(context.Context, *LoginDataReq) (*LoginDataRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginData not implemented")
}
func (UnimplementedLoginServiceServer) LoginWithOtp(context.Context, *PhoneOtpRequst) (*V2LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginWithOtp not implemented")
}
func (UnimplementedLoginServiceServer) LoginWithEmailOtp(context.Context, *EmailOtpRequest) (*V2LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginWithEmailOtp not implemented")
}
func (UnimplementedLoginServiceServer) GetUserUpdatedPermission(context.Context, *GetUserUpdatedPermissionRequest) (*V2LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserUpdatedPermission not implemented")
}
func (UnimplementedLoginServiceServer) LoginDataByUserId(context.Context, *LoginDataReq) (*LoginDataRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginDataByUserId not implemented")
}
func (UnimplementedLoginServiceServer) GetConnetionOptions(context.Context, *GetConnetionOptionsRequest) (*GetConnectionOptionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConnetionOptions not implemented")
}
func (UnimplementedLoginServiceServer) UpdateUserPassword(context.Context, *UpdateUserPasswordRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserPassword not implemented")
}
func (UnimplementedLoginServiceServer) mustEmbedUnimplementedLoginServiceServer() {}

// UnsafeLoginServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LoginServiceServer will
// result in compilation errors.
type UnsafeLoginServiceServer interface {
	mustEmbedUnimplementedLoginServiceServer()
}

func RegisterLoginServiceServer(s grpc.ServiceRegistrar, srv LoginServiceServer) {
	s.RegisterService(&LoginService_ServiceDesc, srv)
}

func _LoginService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/object_builder_service.LoginService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoginService_LoginData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginDataReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServiceServer).LoginData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/object_builder_service.LoginService/LoginData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServiceServer).LoginData(ctx, req.(*LoginDataReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoginService_LoginWithOtp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PhoneOtpRequst)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServiceServer).LoginWithOtp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/object_builder_service.LoginService/LoginWithOtp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServiceServer).LoginWithOtp(ctx, req.(*PhoneOtpRequst))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoginService_LoginWithEmailOtp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailOtpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServiceServer).LoginWithEmailOtp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/object_builder_service.LoginService/LoginWithEmailOtp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServiceServer).LoginWithEmailOtp(ctx, req.(*EmailOtpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoginService_GetUserUpdatedPermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserUpdatedPermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServiceServer).GetUserUpdatedPermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/object_builder_service.LoginService/GetUserUpdatedPermission",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServiceServer).GetUserUpdatedPermission(ctx, req.(*GetUserUpdatedPermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoginService_LoginDataByUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginDataReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServiceServer).LoginDataByUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/object_builder_service.LoginService/LoginDataByUserId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServiceServer).LoginDataByUserId(ctx, req.(*LoginDataReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoginService_GetConnetionOptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConnetionOptionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServiceServer).GetConnetionOptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/object_builder_service.LoginService/GetConnetionOptions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServiceServer).GetConnetionOptions(ctx, req.(*GetConnetionOptionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoginService_UpdateUserPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServiceServer).UpdateUserPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/object_builder_service.LoginService/UpdateUserPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServiceServer).UpdateUserPassword(ctx, req.(*UpdateUserPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LoginService_ServiceDesc is the grpc.ServiceDesc for LoginService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LoginService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "object_builder_service.LoginService",
	HandlerType: (*LoginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _LoginService_Login_Handler,
		},
		{
			MethodName: "LoginData",
			Handler:    _LoginService_LoginData_Handler,
		},
		{
			MethodName: "LoginWithOtp",
			Handler:    _LoginService_LoginWithOtp_Handler,
		},
		{
			MethodName: "LoginWithEmailOtp",
			Handler:    _LoginService_LoginWithEmailOtp_Handler,
		},
		{
			MethodName: "GetUserUpdatedPermission",
			Handler:    _LoginService_GetUserUpdatedPermission_Handler,
		},
		{
			MethodName: "LoginDataByUserId",
			Handler:    _LoginService_LoginDataByUserId_Handler,
		},
		{
			MethodName: "GetConnetionOptions",
			Handler:    _LoginService_GetConnetionOptions_Handler,
		},
		{
			MethodName: "UpdateUserPassword",
			Handler:    _LoginService_UpdateUserPassword_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "login.proto",
}
