// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.17.0
// source: object_builder.proto

package object_builder_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ObjectBuilderServiceClient is the client API for ObjectBuilderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ObjectBuilderServiceClient interface {
	Create(ctx context.Context, in *CommonMessage, opts ...grpc.CallOption) (*CommonMessage, error)
	GetSingle(ctx context.Context, in *CommonMessage, opts ...grpc.CallOption) (*CommonMessage, error)
	GetList(ctx context.Context, in *CommonMessage, opts ...grpc.CallOption) (*CommonMessage, error)
	GetList2(ctx context.Context, in *CommonMessage, opts ...grpc.CallOption) (*CommonMessage, error)
	GetSingleSlim(ctx context.Context, in *CommonMessage, opts ...grpc.CallOption) (*CommonMessage, error)
	GetListSlim(ctx context.Context, in *CommonMessage, opts ...grpc.CallOption) (*CommonMessage, error)
	GetListSlimV2(ctx context.Context, in *CommonMessage, opts ...grpc.CallOption) (*CommonMessage, error)
	GetRecursiveList(ctx context.Context, in *CommonMessage, opts ...grpc.CallOption) (*CommonMessage, error)
	Update(ctx context.Context, in *CommonMessage, opts ...grpc.CallOption) (*CommonMessage, error)
	Delete(ctx context.Context, in *CommonMessage, opts ...grpc.CallOption) (*CommonMessage, error)
	ManyToManyAppend(ctx context.Context, in *ManyToManyMessage, opts ...grpc.CallOption) (*CommonMessage, error)
	ManyToManyDelete(ctx context.Context, in *ManyToManyMessage, opts ...grpc.CallOption) (*CommonMessage, error)
	GetTableDetails(ctx context.Context, in *CommonMessage, opts ...grpc.CallOption) (*CommonMessage, error)
	GetListInExcel(ctx context.Context, in *CommonMessage, opts ...grpc.CallOption) (*CommonMessage, error)
	Batch(ctx context.Context, in *BatchRequest, opts ...grpc.CallOption) (*CommonMessage, error)
	MultipleUpdate(ctx context.Context, in *CommonMessage, opts ...grpc.CallOption) (*CommonMessage, error)
	MultipleInsert(ctx context.Context, in *CommonMessage, opts ...grpc.CallOption) (*CommonMessage, error)
	GetFinancialAnalytics(ctx context.Context, in *CommonMessage, opts ...grpc.CallOption) (*CommonMessage, error)
	GetGroupReportTables(ctx context.Context, in *CommonMessage, opts ...grpc.CallOption) (*CommonMessage, error)
	GetGroupByField(ctx context.Context, in *CommonMessage, opts ...grpc.CallOption) (*CommonMessage, error)
	DeleteMany(ctx context.Context, in *CommonMessage, opts ...grpc.CallOption) (*CommonMessage, error)
	GroupByColumns(ctx context.Context, in *CommonMessage, opts ...grpc.CallOption) (*CommonMessage, error)
	CopyFromProject(ctx context.Context, in *CopyFromProjectRequestMessage, opts ...grpc.CallOption) (*CommonMessage, error)
	GetListWithOutRelations(ctx context.Context, in *CommonMessage, opts ...grpc.CallOption) (*CommonMessage, error)
	GetListAggregation(ctx context.Context, in *CommonMessage, opts ...grpc.CallOption) (*CommonMessage, error)
	GetListRelationTabInExcel(ctx context.Context, in *CommonMessage, opts ...grpc.CallOption) (*CommonMessage, error)
}

type objectBuilderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewObjectBuilderServiceClient(cc grpc.ClientConnInterface) ObjectBuilderServiceClient {
	return &objectBuilderServiceClient{cc}
}

func (c *objectBuilderServiceClient) Create(ctx context.Context, in *CommonMessage, opts ...grpc.CallOption) (*CommonMessage, error) {
	out := new(CommonMessage)
	err := c.cc.Invoke(ctx, "/object_builder_service.ObjectBuilderService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectBuilderServiceClient) GetSingle(ctx context.Context, in *CommonMessage, opts ...grpc.CallOption) (*CommonMessage, error) {
	out := new(CommonMessage)
	err := c.cc.Invoke(ctx, "/object_builder_service.ObjectBuilderService/GetSingle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectBuilderServiceClient) GetList(ctx context.Context, in *CommonMessage, opts ...grpc.CallOption) (*CommonMessage, error) {
	out := new(CommonMessage)
	err := c.cc.Invoke(ctx, "/object_builder_service.ObjectBuilderService/GetList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectBuilderServiceClient) GetList2(ctx context.Context, in *CommonMessage, opts ...grpc.CallOption) (*CommonMessage, error) {
	out := new(CommonMessage)
	err := c.cc.Invoke(ctx, "/object_builder_service.ObjectBuilderService/GetList2", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectBuilderServiceClient) GetSingleSlim(ctx context.Context, in *CommonMessage, opts ...grpc.CallOption) (*CommonMessage, error) {
	out := new(CommonMessage)
	err := c.cc.Invoke(ctx, "/object_builder_service.ObjectBuilderService/GetSingleSlim", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectBuilderServiceClient) GetListSlim(ctx context.Context, in *CommonMessage, opts ...grpc.CallOption) (*CommonMessage, error) {
	out := new(CommonMessage)
	err := c.cc.Invoke(ctx, "/object_builder_service.ObjectBuilderService/GetListSlim", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectBuilderServiceClient) GetListSlimV2(ctx context.Context, in *CommonMessage, opts ...grpc.CallOption) (*CommonMessage, error) {
	out := new(CommonMessage)
	err := c.cc.Invoke(ctx, "/object_builder_service.ObjectBuilderService/GetListSlimV2", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectBuilderServiceClient) GetRecursiveList(ctx context.Context, in *CommonMessage, opts ...grpc.CallOption) (*CommonMessage, error) {
	out := new(CommonMessage)
	err := c.cc.Invoke(ctx, "/object_builder_service.ObjectBuilderService/GetRecursiveList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectBuilderServiceClient) Update(ctx context.Context, in *CommonMessage, opts ...grpc.CallOption) (*CommonMessage, error) {
	out := new(CommonMessage)
	err := c.cc.Invoke(ctx, "/object_builder_service.ObjectBuilderService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectBuilderServiceClient) Delete(ctx context.Context, in *CommonMessage, opts ...grpc.CallOption) (*CommonMessage, error) {
	out := new(CommonMessage)
	err := c.cc.Invoke(ctx, "/object_builder_service.ObjectBuilderService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectBuilderServiceClient) ManyToManyAppend(ctx context.Context, in *ManyToManyMessage, opts ...grpc.CallOption) (*CommonMessage, error) {
	out := new(CommonMessage)
	err := c.cc.Invoke(ctx, "/object_builder_service.ObjectBuilderService/ManyToManyAppend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectBuilderServiceClient) ManyToManyDelete(ctx context.Context, in *ManyToManyMessage, opts ...grpc.CallOption) (*CommonMessage, error) {
	out := new(CommonMessage)
	err := c.cc.Invoke(ctx, "/object_builder_service.ObjectBuilderService/ManyToManyDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectBuilderServiceClient) GetTableDetails(ctx context.Context, in *CommonMessage, opts ...grpc.CallOption) (*CommonMessage, error) {
	out := new(CommonMessage)
	err := c.cc.Invoke(ctx, "/object_builder_service.ObjectBuilderService/GetTableDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectBuilderServiceClient) GetListInExcel(ctx context.Context, in *CommonMessage, opts ...grpc.CallOption) (*CommonMessage, error) {
	out := new(CommonMessage)
	err := c.cc.Invoke(ctx, "/object_builder_service.ObjectBuilderService/GetListInExcel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectBuilderServiceClient) Batch(ctx context.Context, in *BatchRequest, opts ...grpc.CallOption) (*CommonMessage, error) {
	out := new(CommonMessage)
	err := c.cc.Invoke(ctx, "/object_builder_service.ObjectBuilderService/Batch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectBuilderServiceClient) MultipleUpdate(ctx context.Context, in *CommonMessage, opts ...grpc.CallOption) (*CommonMessage, error) {
	out := new(CommonMessage)
	err := c.cc.Invoke(ctx, "/object_builder_service.ObjectBuilderService/MultipleUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectBuilderServiceClient) MultipleInsert(ctx context.Context, in *CommonMessage, opts ...grpc.CallOption) (*CommonMessage, error) {
	out := new(CommonMessage)
	err := c.cc.Invoke(ctx, "/object_builder_service.ObjectBuilderService/MultipleInsert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectBuilderServiceClient) GetFinancialAnalytics(ctx context.Context, in *CommonMessage, opts ...grpc.CallOption) (*CommonMessage, error) {
	out := new(CommonMessage)
	err := c.cc.Invoke(ctx, "/object_builder_service.ObjectBuilderService/GetFinancialAnalytics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectBuilderServiceClient) GetGroupReportTables(ctx context.Context, in *CommonMessage, opts ...grpc.CallOption) (*CommonMessage, error) {
	out := new(CommonMessage)
	err := c.cc.Invoke(ctx, "/object_builder_service.ObjectBuilderService/GetGroupReportTables", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectBuilderServiceClient) GetGroupByField(ctx context.Context, in *CommonMessage, opts ...grpc.CallOption) (*CommonMessage, error) {
	out := new(CommonMessage)
	err := c.cc.Invoke(ctx, "/object_builder_service.ObjectBuilderService/GetGroupByField", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectBuilderServiceClient) DeleteMany(ctx context.Context, in *CommonMessage, opts ...grpc.CallOption) (*CommonMessage, error) {
	out := new(CommonMessage)
	err := c.cc.Invoke(ctx, "/object_builder_service.ObjectBuilderService/DeleteMany", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectBuilderServiceClient) GroupByColumns(ctx context.Context, in *CommonMessage, opts ...grpc.CallOption) (*CommonMessage, error) {
	out := new(CommonMessage)
	err := c.cc.Invoke(ctx, "/object_builder_service.ObjectBuilderService/GroupByColumns", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectBuilderServiceClient) CopyFromProject(ctx context.Context, in *CopyFromProjectRequestMessage, opts ...grpc.CallOption) (*CommonMessage, error) {
	out := new(CommonMessage)
	err := c.cc.Invoke(ctx, "/object_builder_service.ObjectBuilderService/CopyFromProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectBuilderServiceClient) GetListWithOutRelations(ctx context.Context, in *CommonMessage, opts ...grpc.CallOption) (*CommonMessage, error) {
	out := new(CommonMessage)
	err := c.cc.Invoke(ctx, "/object_builder_service.ObjectBuilderService/GetListWithOutRelations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectBuilderServiceClient) GetListAggregation(ctx context.Context, in *CommonMessage, opts ...grpc.CallOption) (*CommonMessage, error) {
	out := new(CommonMessage)
	err := c.cc.Invoke(ctx, "/object_builder_service.ObjectBuilderService/GetListAggregation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectBuilderServiceClient) GetListRelationTabInExcel(ctx context.Context, in *CommonMessage, opts ...grpc.CallOption) (*CommonMessage, error) {
	out := new(CommonMessage)
	err := c.cc.Invoke(ctx, "/object_builder_service.ObjectBuilderService/GetListRelationTabInExcel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ObjectBuilderServiceServer is the server API for ObjectBuilderService service.
// All implementations must embed UnimplementedObjectBuilderServiceServer
// for forward compatibility
type ObjectBuilderServiceServer interface {
	Create(context.Context, *CommonMessage) (*CommonMessage, error)
	GetSingle(context.Context, *CommonMessage) (*CommonMessage, error)
	GetList(context.Context, *CommonMessage) (*CommonMessage, error)
	GetList2(context.Context, *CommonMessage) (*CommonMessage, error)
	GetSingleSlim(context.Context, *CommonMessage) (*CommonMessage, error)
	GetListSlim(context.Context, *CommonMessage) (*CommonMessage, error)
	GetListSlimV2(context.Context, *CommonMessage) (*CommonMessage, error)
	GetRecursiveList(context.Context, *CommonMessage) (*CommonMessage, error)
	Update(context.Context, *CommonMessage) (*CommonMessage, error)
	Delete(context.Context, *CommonMessage) (*CommonMessage, error)
	ManyToManyAppend(context.Context, *ManyToManyMessage) (*CommonMessage, error)
	ManyToManyDelete(context.Context, *ManyToManyMessage) (*CommonMessage, error)
	GetTableDetails(context.Context, *CommonMessage) (*CommonMessage, error)
	GetListInExcel(context.Context, *CommonMessage) (*CommonMessage, error)
	Batch(context.Context, *BatchRequest) (*CommonMessage, error)
	MultipleUpdate(context.Context, *CommonMessage) (*CommonMessage, error)
	MultipleInsert(context.Context, *CommonMessage) (*CommonMessage, error)
	GetFinancialAnalytics(context.Context, *CommonMessage) (*CommonMessage, error)
	GetGroupReportTables(context.Context, *CommonMessage) (*CommonMessage, error)
	GetGroupByField(context.Context, *CommonMessage) (*CommonMessage, error)
	DeleteMany(context.Context, *CommonMessage) (*CommonMessage, error)
	GroupByColumns(context.Context, *CommonMessage) (*CommonMessage, error)
	CopyFromProject(context.Context, *CopyFromProjectRequestMessage) (*CommonMessage, error)
	GetListWithOutRelations(context.Context, *CommonMessage) (*CommonMessage, error)
	GetListAggregation(context.Context, *CommonMessage) (*CommonMessage, error)
	GetListRelationTabInExcel(context.Context, *CommonMessage) (*CommonMessage, error)
	mustEmbedUnimplementedObjectBuilderServiceServer()
}

// UnimplementedObjectBuilderServiceServer must be embedded to have forward compatible implementations.
type UnimplementedObjectBuilderServiceServer struct {
}

func (UnimplementedObjectBuilderServiceServer) Create(context.Context, *CommonMessage) (*CommonMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedObjectBuilderServiceServer) GetSingle(context.Context, *CommonMessage) (*CommonMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSingle not implemented")
}
func (UnimplementedObjectBuilderServiceServer) GetList(context.Context, *CommonMessage) (*CommonMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetList not implemented")
}
func (UnimplementedObjectBuilderServiceServer) GetList2(context.Context, *CommonMessage) (*CommonMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetList2 not implemented")
}
func (UnimplementedObjectBuilderServiceServer) GetSingleSlim(context.Context, *CommonMessage) (*CommonMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSingleSlim not implemented")
}
func (UnimplementedObjectBuilderServiceServer) GetListSlim(context.Context, *CommonMessage) (*CommonMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetListSlim not implemented")
}
func (UnimplementedObjectBuilderServiceServer) GetListSlimV2(context.Context, *CommonMessage) (*CommonMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetListSlimV2 not implemented")
}
func (UnimplementedObjectBuilderServiceServer) GetRecursiveList(context.Context, *CommonMessage) (*CommonMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRecursiveList not implemented")
}
func (UnimplementedObjectBuilderServiceServer) Update(context.Context, *CommonMessage) (*CommonMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedObjectBuilderServiceServer) Delete(context.Context, *CommonMessage) (*CommonMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedObjectBuilderServiceServer) ManyToManyAppend(context.Context, *ManyToManyMessage) (*CommonMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ManyToManyAppend not implemented")
}
func (UnimplementedObjectBuilderServiceServer) ManyToManyDelete(context.Context, *ManyToManyMessage) (*CommonMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ManyToManyDelete not implemented")
}
func (UnimplementedObjectBuilderServiceServer) GetTableDetails(context.Context, *CommonMessage) (*CommonMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTableDetails not implemented")
}
func (UnimplementedObjectBuilderServiceServer) GetListInExcel(context.Context, *CommonMessage) (*CommonMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetListInExcel not implemented")
}
func (UnimplementedObjectBuilderServiceServer) Batch(context.Context, *BatchRequest) (*CommonMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Batch not implemented")
}
func (UnimplementedObjectBuilderServiceServer) MultipleUpdate(context.Context, *CommonMessage) (*CommonMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MultipleUpdate not implemented")
}
func (UnimplementedObjectBuilderServiceServer) MultipleInsert(context.Context, *CommonMessage) (*CommonMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MultipleInsert not implemented")
}
func (UnimplementedObjectBuilderServiceServer) GetFinancialAnalytics(context.Context, *CommonMessage) (*CommonMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFinancialAnalytics not implemented")
}
func (UnimplementedObjectBuilderServiceServer) GetGroupReportTables(context.Context, *CommonMessage) (*CommonMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGroupReportTables not implemented")
}
func (UnimplementedObjectBuilderServiceServer) GetGroupByField(context.Context, *CommonMessage) (*CommonMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGroupByField not implemented")
}
func (UnimplementedObjectBuilderServiceServer) DeleteMany(context.Context, *CommonMessage) (*CommonMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMany not implemented")
}
func (UnimplementedObjectBuilderServiceServer) GroupByColumns(context.Context, *CommonMessage) (*CommonMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GroupByColumns not implemented")
}
func (UnimplementedObjectBuilderServiceServer) CopyFromProject(context.Context, *CopyFromProjectRequestMessage) (*CommonMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CopyFromProject not implemented")
}
func (UnimplementedObjectBuilderServiceServer) GetListWithOutRelations(context.Context, *CommonMessage) (*CommonMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetListWithOutRelations not implemented")
}
func (UnimplementedObjectBuilderServiceServer) GetListAggregation(context.Context, *CommonMessage) (*CommonMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetListAggregation not implemented")
}
func (UnimplementedObjectBuilderServiceServer) GetListRelationTabInExcel(context.Context, *CommonMessage) (*CommonMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetListRelationTabInExcel not implemented")
}
func (UnimplementedObjectBuilderServiceServer) mustEmbedUnimplementedObjectBuilderServiceServer() {}

// UnsafeObjectBuilderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ObjectBuilderServiceServer will
// result in compilation errors.
type UnsafeObjectBuilderServiceServer interface {
	mustEmbedUnimplementedObjectBuilderServiceServer()
}

func RegisterObjectBuilderServiceServer(s grpc.ServiceRegistrar, srv ObjectBuilderServiceServer) {
	s.RegisterService(&ObjectBuilderService_ServiceDesc, srv)
}

func _ObjectBuilderService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommonMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectBuilderServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/object_builder_service.ObjectBuilderService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectBuilderServiceServer).Create(ctx, req.(*CommonMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectBuilderService_GetSingle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommonMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectBuilderServiceServer).GetSingle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/object_builder_service.ObjectBuilderService/GetSingle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectBuilderServiceServer).GetSingle(ctx, req.(*CommonMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectBuilderService_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommonMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectBuilderServiceServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/object_builder_service.ObjectBuilderService/GetList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectBuilderServiceServer).GetList(ctx, req.(*CommonMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectBuilderService_GetList2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommonMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectBuilderServiceServer).GetList2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/object_builder_service.ObjectBuilderService/GetList2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectBuilderServiceServer).GetList2(ctx, req.(*CommonMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectBuilderService_GetSingleSlim_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommonMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectBuilderServiceServer).GetSingleSlim(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/object_builder_service.ObjectBuilderService/GetSingleSlim",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectBuilderServiceServer).GetSingleSlim(ctx, req.(*CommonMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectBuilderService_GetListSlim_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommonMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectBuilderServiceServer).GetListSlim(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/object_builder_service.ObjectBuilderService/GetListSlim",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectBuilderServiceServer).GetListSlim(ctx, req.(*CommonMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectBuilderService_GetListSlimV2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommonMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectBuilderServiceServer).GetListSlimV2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/object_builder_service.ObjectBuilderService/GetListSlimV2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectBuilderServiceServer).GetListSlimV2(ctx, req.(*CommonMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectBuilderService_GetRecursiveList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommonMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectBuilderServiceServer).GetRecursiveList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/object_builder_service.ObjectBuilderService/GetRecursiveList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectBuilderServiceServer).GetRecursiveList(ctx, req.(*CommonMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectBuilderService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommonMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectBuilderServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/object_builder_service.ObjectBuilderService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectBuilderServiceServer).Update(ctx, req.(*CommonMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectBuilderService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommonMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectBuilderServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/object_builder_service.ObjectBuilderService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectBuilderServiceServer).Delete(ctx, req.(*CommonMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectBuilderService_ManyToManyAppend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManyToManyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectBuilderServiceServer).ManyToManyAppend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/object_builder_service.ObjectBuilderService/ManyToManyAppend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectBuilderServiceServer).ManyToManyAppend(ctx, req.(*ManyToManyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectBuilderService_ManyToManyDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManyToManyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectBuilderServiceServer).ManyToManyDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/object_builder_service.ObjectBuilderService/ManyToManyDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectBuilderServiceServer).ManyToManyDelete(ctx, req.(*ManyToManyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectBuilderService_GetTableDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommonMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectBuilderServiceServer).GetTableDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/object_builder_service.ObjectBuilderService/GetTableDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectBuilderServiceServer).GetTableDetails(ctx, req.(*CommonMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectBuilderService_GetListInExcel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommonMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectBuilderServiceServer).GetListInExcel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/object_builder_service.ObjectBuilderService/GetListInExcel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectBuilderServiceServer).GetListInExcel(ctx, req.(*CommonMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectBuilderService_Batch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectBuilderServiceServer).Batch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/object_builder_service.ObjectBuilderService/Batch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectBuilderServiceServer).Batch(ctx, req.(*BatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectBuilderService_MultipleUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommonMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectBuilderServiceServer).MultipleUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/object_builder_service.ObjectBuilderService/MultipleUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectBuilderServiceServer).MultipleUpdate(ctx, req.(*CommonMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectBuilderService_MultipleInsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommonMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectBuilderServiceServer).MultipleInsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/object_builder_service.ObjectBuilderService/MultipleInsert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectBuilderServiceServer).MultipleInsert(ctx, req.(*CommonMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectBuilderService_GetFinancialAnalytics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommonMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectBuilderServiceServer).GetFinancialAnalytics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/object_builder_service.ObjectBuilderService/GetFinancialAnalytics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectBuilderServiceServer).GetFinancialAnalytics(ctx, req.(*CommonMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectBuilderService_GetGroupReportTables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommonMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectBuilderServiceServer).GetGroupReportTables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/object_builder_service.ObjectBuilderService/GetGroupReportTables",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectBuilderServiceServer).GetGroupReportTables(ctx, req.(*CommonMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectBuilderService_GetGroupByField_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommonMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectBuilderServiceServer).GetGroupByField(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/object_builder_service.ObjectBuilderService/GetGroupByField",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectBuilderServiceServer).GetGroupByField(ctx, req.(*CommonMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectBuilderService_DeleteMany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommonMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectBuilderServiceServer).DeleteMany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/object_builder_service.ObjectBuilderService/DeleteMany",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectBuilderServiceServer).DeleteMany(ctx, req.(*CommonMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectBuilderService_GroupByColumns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommonMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectBuilderServiceServer).GroupByColumns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/object_builder_service.ObjectBuilderService/GroupByColumns",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectBuilderServiceServer).GroupByColumns(ctx, req.(*CommonMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectBuilderService_CopyFromProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CopyFromProjectRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectBuilderServiceServer).CopyFromProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/object_builder_service.ObjectBuilderService/CopyFromProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectBuilderServiceServer).CopyFromProject(ctx, req.(*CopyFromProjectRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectBuilderService_GetListWithOutRelations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommonMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectBuilderServiceServer).GetListWithOutRelations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/object_builder_service.ObjectBuilderService/GetListWithOutRelations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectBuilderServiceServer).GetListWithOutRelations(ctx, req.(*CommonMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectBuilderService_GetListAggregation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommonMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectBuilderServiceServer).GetListAggregation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/object_builder_service.ObjectBuilderService/GetListAggregation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectBuilderServiceServer).GetListAggregation(ctx, req.(*CommonMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectBuilderService_GetListRelationTabInExcel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommonMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectBuilderServiceServer).GetListRelationTabInExcel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/object_builder_service.ObjectBuilderService/GetListRelationTabInExcel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectBuilderServiceServer).GetListRelationTabInExcel(ctx, req.(*CommonMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// ObjectBuilderService_ServiceDesc is the grpc.ServiceDesc for ObjectBuilderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ObjectBuilderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "object_builder_service.ObjectBuilderService",
	HandlerType: (*ObjectBuilderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ObjectBuilderService_Create_Handler,
		},
		{
			MethodName: "GetSingle",
			Handler:    _ObjectBuilderService_GetSingle_Handler,
		},
		{
			MethodName: "GetList",
			Handler:    _ObjectBuilderService_GetList_Handler,
		},
		{
			MethodName: "GetList2",
			Handler:    _ObjectBuilderService_GetList2_Handler,
		},
		{
			MethodName: "GetSingleSlim",
			Handler:    _ObjectBuilderService_GetSingleSlim_Handler,
		},
		{
			MethodName: "GetListSlim",
			Handler:    _ObjectBuilderService_GetListSlim_Handler,
		},
		{
			MethodName: "GetListSlimV2",
			Handler:    _ObjectBuilderService_GetListSlimV2_Handler,
		},
		{
			MethodName: "GetRecursiveList",
			Handler:    _ObjectBuilderService_GetRecursiveList_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ObjectBuilderService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ObjectBuilderService_Delete_Handler,
		},
		{
			MethodName: "ManyToManyAppend",
			Handler:    _ObjectBuilderService_ManyToManyAppend_Handler,
		},
		{
			MethodName: "ManyToManyDelete",
			Handler:    _ObjectBuilderService_ManyToManyDelete_Handler,
		},
		{
			MethodName: "GetTableDetails",
			Handler:    _ObjectBuilderService_GetTableDetails_Handler,
		},
		{
			MethodName: "GetListInExcel",
			Handler:    _ObjectBuilderService_GetListInExcel_Handler,
		},
		{
			MethodName: "Batch",
			Handler:    _ObjectBuilderService_Batch_Handler,
		},
		{
			MethodName: "MultipleUpdate",
			Handler:    _ObjectBuilderService_MultipleUpdate_Handler,
		},
		{
			MethodName: "MultipleInsert",
			Handler:    _ObjectBuilderService_MultipleInsert_Handler,
		},
		{
			MethodName: "GetFinancialAnalytics",
			Handler:    _ObjectBuilderService_GetFinancialAnalytics_Handler,
		},
		{
			MethodName: "GetGroupReportTables",
			Handler:    _ObjectBuilderService_GetGroupReportTables_Handler,
		},
		{
			MethodName: "GetGroupByField",
			Handler:    _ObjectBuilderService_GetGroupByField_Handler,
		},
		{
			MethodName: "DeleteMany",
			Handler:    _ObjectBuilderService_DeleteMany_Handler,
		},
		{
			MethodName: "GroupByColumns",
			Handler:    _ObjectBuilderService_GroupByColumns_Handler,
		},
		{
			MethodName: "CopyFromProject",
			Handler:    _ObjectBuilderService_CopyFromProject_Handler,
		},
		{
			MethodName: "GetListWithOutRelations",
			Handler:    _ObjectBuilderService_GetListWithOutRelations_Handler,
		},
		{
			MethodName: "GetListAggregation",
			Handler:    _ObjectBuilderService_GetListAggregation_Handler,
		},
		{
			MethodName: "GetListRelationTabInExcel",
			Handler:    _ObjectBuilderService_GetListRelationTabInExcel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "object_builder.proto",
}
