// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.17.3
// source: version_history.proto

package object_builder_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	VersionHistoryService_Create_FullMethodName  = "/object_builder_service.VersionHistoryService/Create"
	VersionHistoryService_GatAll_FullMethodName  = "/object_builder_service.VersionHistoryService/GatAll"
	VersionHistoryService_Update_FullMethodName  = "/object_builder_service.VersionHistoryService/Update"
	VersionHistoryService_GetByID_FullMethodName = "/object_builder_service.VersionHistoryService/GetByID"
)

// VersionHistoryServiceClient is the client API for VersionHistoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VersionHistoryServiceClient interface {
	Create(ctx context.Context, in *CreateVersionHistoryRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GatAll(ctx context.Context, in *GetAllRquest, opts ...grpc.CallOption) (*ListVersionHistory, error)
	Update(ctx context.Context, in *UsedForEnvRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetByID(ctx context.Context, in *VersionHistoryPrimaryKey, opts ...grpc.CallOption) (*VersionHistory, error)
}

type versionHistoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVersionHistoryServiceClient(cc grpc.ClientConnInterface) VersionHistoryServiceClient {
	return &versionHistoryServiceClient{cc}
}

func (c *versionHistoryServiceClient) Create(ctx context.Context, in *CreateVersionHistoryRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, VersionHistoryService_Create_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *versionHistoryServiceClient) GatAll(ctx context.Context, in *GetAllRquest, opts ...grpc.CallOption) (*ListVersionHistory, error) {
	out := new(ListVersionHistory)
	err := c.cc.Invoke(ctx, VersionHistoryService_GatAll_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *versionHistoryServiceClient) Update(ctx context.Context, in *UsedForEnvRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, VersionHistoryService_Update_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *versionHistoryServiceClient) GetByID(ctx context.Context, in *VersionHistoryPrimaryKey, opts ...grpc.CallOption) (*VersionHistory, error) {
	out := new(VersionHistory)
	err := c.cc.Invoke(ctx, VersionHistoryService_GetByID_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VersionHistoryServiceServer is the server API for VersionHistoryService service.
// All implementations must embed UnimplementedVersionHistoryServiceServer
// for forward compatibility
type VersionHistoryServiceServer interface {
	Create(context.Context, *CreateVersionHistoryRequest) (*emptypb.Empty, error)
	GatAll(context.Context, *GetAllRquest) (*ListVersionHistory, error)
	Update(context.Context, *UsedForEnvRequest) (*emptypb.Empty, error)
	GetByID(context.Context, *VersionHistoryPrimaryKey) (*VersionHistory, error)
	mustEmbedUnimplementedVersionHistoryServiceServer()
}

// UnimplementedVersionHistoryServiceServer must be embedded to have forward compatible implementations.
type UnimplementedVersionHistoryServiceServer struct {
}

func (UnimplementedVersionHistoryServiceServer) Create(context.Context, *CreateVersionHistoryRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedVersionHistoryServiceServer) GatAll(context.Context, *GetAllRquest) (*ListVersionHistory, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GatAll not implemented")
}
func (UnimplementedVersionHistoryServiceServer) Update(context.Context, *UsedForEnvRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedVersionHistoryServiceServer) GetByID(context.Context, *VersionHistoryPrimaryKey) (*VersionHistory, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByID not implemented")
}
func (UnimplementedVersionHistoryServiceServer) mustEmbedUnimplementedVersionHistoryServiceServer() {}

// UnsafeVersionHistoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VersionHistoryServiceServer will
// result in compilation errors.
type UnsafeVersionHistoryServiceServer interface {
	mustEmbedUnimplementedVersionHistoryServiceServer()
}

func RegisterVersionHistoryServiceServer(s grpc.ServiceRegistrar, srv VersionHistoryServiceServer) {
	s.RegisterService(&VersionHistoryService_ServiceDesc, srv)
}

func _VersionHistoryService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVersionHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VersionHistoryServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VersionHistoryService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VersionHistoryServiceServer).Create(ctx, req.(*CreateVersionHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VersionHistoryService_GatAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllRquest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VersionHistoryServiceServer).GatAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VersionHistoryService_GatAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VersionHistoryServiceServer).GatAll(ctx, req.(*GetAllRquest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VersionHistoryService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsedForEnvRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VersionHistoryServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VersionHistoryService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VersionHistoryServiceServer).Update(ctx, req.(*UsedForEnvRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VersionHistoryService_GetByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionHistoryPrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VersionHistoryServiceServer).GetByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VersionHistoryService_GetByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VersionHistoryServiceServer).GetByID(ctx, req.(*VersionHistoryPrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

// VersionHistoryService_ServiceDesc is the grpc.ServiceDesc for VersionHistoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VersionHistoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "object_builder_service.VersionHistoryService",
	HandlerType: (*VersionHistoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _VersionHistoryService_Create_Handler,
		},
		{
			MethodName: "GatAll",
			Handler:    _VersionHistoryService_GatAll_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _VersionHistoryService_Update_Handler,
		},
		{
			MethodName: "GetByID",
			Handler:    _VersionHistoryService_GetByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "version_history.proto",
}
