// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.2
// source: company_ping_service.proto

package company_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CompanyPingServiceClient is the client API for CompanyPingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CompanyPingServiceClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type companyPingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCompanyPingServiceClient(cc grpc.ClientConnInterface) CompanyPingServiceClient {
	return &companyPingServiceClient{cc}
}

func (c *companyPingServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, "/company_service.CompanyPingService/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CompanyPingServiceServer is the server API for CompanyPingService service.
// All implementations must embed UnimplementedCompanyPingServiceServer
// for forward compatibility
type CompanyPingServiceServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	mustEmbedUnimplementedCompanyPingServiceServer()
}

// UnimplementedCompanyPingServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCompanyPingServiceServer struct {
}

func (UnimplementedCompanyPingServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedCompanyPingServiceServer) mustEmbedUnimplementedCompanyPingServiceServer() {}

// UnsafeCompanyPingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CompanyPingServiceServer will
// result in compilation errors.
type UnsafeCompanyPingServiceServer interface {
	mustEmbedUnimplementedCompanyPingServiceServer()
}

func RegisterCompanyPingServiceServer(s grpc.ServiceRegistrar, srv CompanyPingServiceServer) {
	s.RegisterService(&CompanyPingService_ServiceDesc, srv)
}

func _CompanyPingService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompanyPingServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/company_service.CompanyPingService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompanyPingServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CompanyPingService_ServiceDesc is the grpc.ServiceDesc for CompanyPingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CompanyPingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "company_service.CompanyPingService",
	HandlerType: (*CompanyPingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _CompanyPingService_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "company_ping_service.proto",
}
