// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.17.0
// source: auth_ping_service.proto

package auth_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AuthPingServiceClient is the client API for AuthPingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthPingServiceClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type authPingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthPingServiceClient(cc grpc.ClientConnInterface) AuthPingServiceClient {
	return &authPingServiceClient{cc}
}

func (c *authPingServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, "/auth_service.AuthPingService/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthPingServiceServer is the server API for AuthPingService service.
// All implementations must embed UnimplementedAuthPingServiceServer
// for forward compatibility
type AuthPingServiceServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	mustEmbedUnimplementedAuthPingServiceServer()
}

// UnimplementedAuthPingServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAuthPingServiceServer struct {
}

func (UnimplementedAuthPingServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedAuthPingServiceServer) mustEmbedUnimplementedAuthPingServiceServer() {}

// UnsafeAuthPingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthPingServiceServer will
// result in compilation errors.
type UnsafeAuthPingServiceServer interface {
	mustEmbedUnimplementedAuthPingServiceServer()
}

func RegisterAuthPingServiceServer(s grpc.ServiceRegistrar, srv AuthPingServiceServer) {
	s.RegisterService(&AuthPingService_ServiceDesc, srv)
}

func _AuthPingService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthPingServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth_service.AuthPingService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthPingServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthPingService_ServiceDesc is the grpc.ServiceDesc for AuthPingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthPingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth_service.AuthPingService",
	HandlerType: (*AuthPingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _AuthPingService_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth_ping_service.proto",
}
