// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.3
// source: login_platform_type.proto

package auth_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LoginPlatformTypeLoginServiceClient is the client API for LoginPlatformTypeLoginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LoginPlatformTypeLoginServiceClient interface {
	CreateLoginPlatformType(ctx context.Context, in *LoginPlatform, opts ...grpc.CallOption) (*LoginPlatform, error)
	UpdateLoginPlatformType(ctx context.Context, in *UpdateLoginPlatformTypeRequest, opts ...grpc.CallOption) (*LoginPlatform, error)
	GetLoginPlatformType(ctx context.Context, in *LoginPlatformTypePrimaryKey, opts ...grpc.CallOption) (*LoginPlatform, error)
	GetListLoginPlatformType(ctx context.Context, in *GetListLoginPlatformTypeRequest, opts ...grpc.CallOption) (*GetListLoginPlatformTypeResponse, error)
	DeleteLoginPlatformType(ctx context.Context, in *LoginPlatformTypePrimaryKey, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type loginPlatformTypeLoginServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLoginPlatformTypeLoginServiceClient(cc grpc.ClientConnInterface) LoginPlatformTypeLoginServiceClient {
	return &loginPlatformTypeLoginServiceClient{cc}
}

func (c *loginPlatformTypeLoginServiceClient) CreateLoginPlatformType(ctx context.Context, in *LoginPlatform, opts ...grpc.CallOption) (*LoginPlatform, error) {
	out := new(LoginPlatform)
	err := c.cc.Invoke(ctx, "/auth_service.LoginPlatformTypeLoginService/CreateLoginPlatformType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginPlatformTypeLoginServiceClient) UpdateLoginPlatformType(ctx context.Context, in *UpdateLoginPlatformTypeRequest, opts ...grpc.CallOption) (*LoginPlatform, error) {
	out := new(LoginPlatform)
	err := c.cc.Invoke(ctx, "/auth_service.LoginPlatformTypeLoginService/UpdateLoginPlatformType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginPlatformTypeLoginServiceClient) GetLoginPlatformType(ctx context.Context, in *LoginPlatformTypePrimaryKey, opts ...grpc.CallOption) (*LoginPlatform, error) {
	out := new(LoginPlatform)
	err := c.cc.Invoke(ctx, "/auth_service.LoginPlatformTypeLoginService/GetLoginPlatformType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginPlatformTypeLoginServiceClient) GetListLoginPlatformType(ctx context.Context, in *GetListLoginPlatformTypeRequest, opts ...grpc.CallOption) (*GetListLoginPlatformTypeResponse, error) {
	out := new(GetListLoginPlatformTypeResponse)
	err := c.cc.Invoke(ctx, "/auth_service.LoginPlatformTypeLoginService/GetListLoginPlatformType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginPlatformTypeLoginServiceClient) DeleteLoginPlatformType(ctx context.Context, in *LoginPlatformTypePrimaryKey, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/auth_service.LoginPlatformTypeLoginService/DeleteLoginPlatformType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoginPlatformTypeLoginServiceServer is the server API for LoginPlatformTypeLoginService service.
// All implementations must embed UnimplementedLoginPlatformTypeLoginServiceServer
// for forward compatibility
type LoginPlatformTypeLoginServiceServer interface {
	CreateLoginPlatformType(context.Context, *LoginPlatform) (*LoginPlatform, error)
	UpdateLoginPlatformType(context.Context, *UpdateLoginPlatformTypeRequest) (*LoginPlatform, error)
	GetLoginPlatformType(context.Context, *LoginPlatformTypePrimaryKey) (*LoginPlatform, error)
	GetListLoginPlatformType(context.Context, *GetListLoginPlatformTypeRequest) (*GetListLoginPlatformTypeResponse, error)
	DeleteLoginPlatformType(context.Context, *LoginPlatformTypePrimaryKey) (*emptypb.Empty, error)
	mustEmbedUnimplementedLoginPlatformTypeLoginServiceServer()
}

// UnimplementedLoginPlatformTypeLoginServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLoginPlatformTypeLoginServiceServer struct {
}

func (UnimplementedLoginPlatformTypeLoginServiceServer) CreateLoginPlatformType(context.Context, *LoginPlatform) (*LoginPlatform, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLoginPlatformType not implemented")
}
func (UnimplementedLoginPlatformTypeLoginServiceServer) UpdateLoginPlatformType(context.Context, *UpdateLoginPlatformTypeRequest) (*LoginPlatform, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateLoginPlatformType not implemented")
}
func (UnimplementedLoginPlatformTypeLoginServiceServer) GetLoginPlatformType(context.Context, *LoginPlatformTypePrimaryKey) (*LoginPlatform, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLoginPlatformType not implemented")
}
func (UnimplementedLoginPlatformTypeLoginServiceServer) GetListLoginPlatformType(context.Context, *GetListLoginPlatformTypeRequest) (*GetListLoginPlatformTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetListLoginPlatformType not implemented")
}
func (UnimplementedLoginPlatformTypeLoginServiceServer) DeleteLoginPlatformType(context.Context, *LoginPlatformTypePrimaryKey) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteLoginPlatformType not implemented")
}
func (UnimplementedLoginPlatformTypeLoginServiceServer) mustEmbedUnimplementedLoginPlatformTypeLoginServiceServer() {
}

// UnsafeLoginPlatformTypeLoginServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LoginPlatformTypeLoginServiceServer will
// result in compilation errors.
type UnsafeLoginPlatformTypeLoginServiceServer interface {
	mustEmbedUnimplementedLoginPlatformTypeLoginServiceServer()
}

func RegisterLoginPlatformTypeLoginServiceServer(s grpc.ServiceRegistrar, srv LoginPlatformTypeLoginServiceServer) {
	s.RegisterService(&LoginPlatformTypeLoginService_ServiceDesc, srv)
}

func _LoginPlatformTypeLoginService_CreateLoginPlatformType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginPlatform)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginPlatformTypeLoginServiceServer).CreateLoginPlatformType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth_service.LoginPlatformTypeLoginService/CreateLoginPlatformType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginPlatformTypeLoginServiceServer).CreateLoginPlatformType(ctx, req.(*LoginPlatform))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoginPlatformTypeLoginService_UpdateLoginPlatformType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLoginPlatformTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginPlatformTypeLoginServiceServer).UpdateLoginPlatformType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth_service.LoginPlatformTypeLoginService/UpdateLoginPlatformType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginPlatformTypeLoginServiceServer).UpdateLoginPlatformType(ctx, req.(*UpdateLoginPlatformTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoginPlatformTypeLoginService_GetLoginPlatformType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginPlatformTypePrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginPlatformTypeLoginServiceServer).GetLoginPlatformType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth_service.LoginPlatformTypeLoginService/GetLoginPlatformType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginPlatformTypeLoginServiceServer).GetLoginPlatformType(ctx, req.(*LoginPlatformTypePrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoginPlatformTypeLoginService_GetListLoginPlatformType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListLoginPlatformTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginPlatformTypeLoginServiceServer).GetListLoginPlatformType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth_service.LoginPlatformTypeLoginService/GetListLoginPlatformType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginPlatformTypeLoginServiceServer).GetListLoginPlatformType(ctx, req.(*GetListLoginPlatformTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoginPlatformTypeLoginService_DeleteLoginPlatformType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginPlatformTypePrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginPlatformTypeLoginServiceServer).DeleteLoginPlatformType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth_service.LoginPlatformTypeLoginService/DeleteLoginPlatformType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginPlatformTypeLoginServiceServer).DeleteLoginPlatformType(ctx, req.(*LoginPlatformTypePrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

// LoginPlatformTypeLoginService_ServiceDesc is the grpc.ServiceDesc for LoginPlatformTypeLoginService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LoginPlatformTypeLoginService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth_service.LoginPlatformTypeLoginService",
	HandlerType: (*LoginPlatformTypeLoginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLoginPlatformType",
			Handler:    _LoginPlatformTypeLoginService_CreateLoginPlatformType_Handler,
		},
		{
			MethodName: "UpdateLoginPlatformType",
			Handler:    _LoginPlatformTypeLoginService_UpdateLoginPlatformType_Handler,
		},
		{
			MethodName: "GetLoginPlatformType",
			Handler:    _LoginPlatformTypeLoginService_GetLoginPlatformType_Handler,
		},
		{
			MethodName: "GetListLoginPlatformType",
			Handler:    _LoginPlatformTypeLoginService_GetListLoginPlatformType_Handler,
		},
		{
			MethodName: "DeleteLoginPlatformType",
			Handler:    _LoginPlatformTypeLoginService_DeleteLoginPlatformType_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "login_platform_type.proto",
}
